#!/usr/bin/env python3
"""Train the keyhog mixture-of-experts secret scorer and serialize weights.bin.

This is the rebuilt training pipeline referenced by
`crates/scanner/src/ml_scorer/ml_weights.rs` ("Generated by: python3 ml/train_classifier.py").
The model architecture and the serialized layout match `ml_scorer.rs` exactly:

  gate:   Linear(D, 6) -> softmax over 6 experts
  expert: Linear(D, 32) -> ReLU -> Linear(32, 16) -> ReLU -> Linear(16, 1)
  output: fast_sigmoid( sum_e softmax(gate)[e] * expert_logit_e )

`fast_sigmoid` is the exact serve-time nonlinearity (0.5 + 0.5*x/(1+|x|)); we
train through it so the trained probabilities are the ones the Rust scanner
produces (modulo the |x|>6 hard-clamp, which only affects already-saturated
logits and never flips a threshold decision).

Serialized order (little-endian f32), matching ml_weights.rs offsets:
  gate.weight[6,D], gate.bias[6],
  then per expert e in 0..6:
    fc1.weight[32,D], fc1.bias[32], fc2.weight[16,32], fc2.bias[16],
    fc3.weight[1,16], fc3.bias[1]

Usage:
  python3 ml/corpus.py --out ml/data/corpus.jsonl
  python3 ml/train_classifier.py --corpus ml/data/corpus.jsonl \
      --out crates/scanner/src/weights.bin --features 55 --compare
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import math
import os
import pathlib
import shutil
import struct
import sys

import numpy as np

import config_lists
import detector_policy
import rust_features

EXPERT_COUNT = 6
FC1 = 32
FC2 = 16
CURRENT_MODEL_CARD = "crates/scanner/src/model_card.json"
CURRENT_QUANTIZED_MODEL = "crates/scanner/src/quantized_moe.bin"
QUANTIZED_MODEL_FORMAT_VERSION = 1
QUANTIZED_FEATURE_SCHEMA_VERSION = 1
QUANTIZED_FRACTIONAL_BITS = 7
QUANTIZED_ROUNDING_TIES_AWAY = 1
REAL_RECALL_FLOOR = 0.40
REAL_F1_FLOOR = 0.78
REAL_PRECISION_FLOOR = 0.70
RECALL_SENSITIVE_CLASS_FLOOR = 0.50
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_DIFFERENTIAL_RESULTS = "benchmarks/results"
DEFAULT_DIFFERENTIAL_CORPUS = "creddata"
PATTERN_CALIBRATION_SCHEMA_VERSION = 1
PATTERN_CALIBRATION_IDENTITY_SCHEMA = (
    "detector-corpus-v1:detector-id:pattern-index:"
    "candidate-channel:source-role:context-class"
)
PATTERN_CALIBRATION_DEFAULT_FLOORS = {
    "blocking_score": REAL_RECALL_FLOOR,
    "minimum_positive_support": 2,
    "minimum_negative_support": 2,
    "minimum_recall": 1.0,
    "maximum_brier_score": 0.25,
    "maximum_ece": 0.10,
}
PATTERN_CALIBRATION_SOURCE_ROLES = frozenset({
    "structured-assignment-value",
    "environment-assignment-value",
    "string-literal",
    "command-argument-value",
    "command-option-declaration",
    "header-value",
    "url-authority-userinfo",
    "connection-string",
    "standalone-token",
    "pem-block",
    "regex-rule-definition",
    "identifier-type-member-name",
    "prose-documentation",
    "test-fixture",
    "generated-vendor-material",
    "unknown",
})
PATTERN_CALIBRATION_CONTEXT_CLASSES = frozenset({
    "unattributed",
    "unsupported-context",
    "required-evidence-missing",
    "weak-anchor",
    "generic-detector",
    "generic-assignment",
    "entropy-only",
    "test-fixture",
    "documentation",
    "rule-definition",
    "identifier",
    "option-declaration",
    "generated-material",
    "source-role-mismatch",
    "vendor-pattern",
    "structural-grammar",
    "required-companion",
    "checksum-valid",
    "live-verification",
})
PATTERN_CALIBRATION_MAX_DETECTOR_ID_BYTES = 128


def valid_detector_slug(value):
    return (
        isinstance(value, str)
        and 0 < len(value) <= PATTERN_CALIBRATION_MAX_DETECTOR_ID_BYTES
        and all(ch.isascii() and (ch.islower() or ch.isdigit() or ch == "-") for ch in value)
    )


def valid_model_version(value):
    return (
        isinstance(value, str)
        and len(value) == len("moe-v1-") + 16
        and value.startswith("moe-v1-")
        and all(ch in "0123456789abcdef" for ch in value[len("moe-v1-"):])
    )


def fast_sigmoid(x):
    import torch

    return 0.5 + 0.5 * x / (1.0 + x.abs())


def load_corpus(path: str, num_features: int):
    kp, sk, tk, pk = config_lists.DEFAULT_LISTS
    records, y, kinds, detectors = [], [], [], []
    with open(path) as fh:
        for line_no, line in enumerate(fh, start=1):
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            records.append(rec)
            y.append(float(rec["label"]))
            kinds.append(rec.get("kind", ""))
            detector_id = _required_corpus_field(path, line_no, rec, "detector_id")
            channel = _required_corpus_field(path, line_no, rec, "candidate_channel")
            detector_policy.validate_candidate_channel(detector_id, channel)
            detectors.append(detector_id)
    X = rust_features.compute_feature_matrix(records, (kp, sk, tk, pk), num_features)
    return X, np.asarray(y, dtype=np.float32), kinds, detectors


def build_model(num_features: int):
    import torch.nn as nn

    class Expert(nn.Module):
        def __init__(self, d):
            super().__init__()
            self.fc1 = nn.Linear(d, FC1)
            self.fc2 = nn.Linear(FC1, FC2)
            self.fc3 = nn.Linear(FC2, 1)

        def forward(self, x):
            import torch.nn.functional as F

            h = F.relu(self.fc1(x))
            h = F.relu(self.fc2(h))
            return self.fc3(h)  # [N,1] logit

    class MoE(nn.Module):
        def __init__(self, d):
            super().__init__()
            self.gate = nn.Linear(d, EXPERT_COUNT)
            self.experts = nn.ModuleList([Expert(d) for _ in range(EXPERT_COUNT)])

        def forward(self, x):
            import torch
            import torch.nn.functional as F

            gate_probs = F.softmax(self.gate(x), dim=1)  # [N,6]
            expert_logits = torch.cat([e(x) for e in self.experts], dim=1)  # [N,6]
            score_logit = (gate_probs * expert_logits).sum(dim=1)  # [N]
            return fast_sigmoid(score_logit)

    return MoE(num_features)


def load_serialized_weights(model, path: str, num_features: int) -> None:
    """Load the exact Rust `weights.bin` layout into a training model.

    This supports recall-preserving fine-tuning of a shipped 55-feature model
    instead of forcing every corpus correction to restart from random weights.
    The loader is deliberately strict: an architecture or feature-count mismatch
    fails before training rather than partially initializing the model.
    """
    import torch

    flat = np.fromfile(path, dtype="<f4")
    state = model.state_dict()
    names = ["gate.weight", "gate.bias"]
    for expert in range(EXPERT_COUNT):
        names.extend(
            [
                f"experts.{expert}.fc1.weight",
                f"experts.{expert}.fc1.bias",
                f"experts.{expert}.fc2.weight",
                f"experts.{expert}.fc2.bias",
                f"experts.{expert}.fc3.weight",
                f"experts.{expert}.fc3.bias",
            ]
        )
    expected = sum(state[name].numel() for name in names)
    if flat.size != expected:
        raise ValueError(
            f"{path}: serialized model has {flat.size} f32 values; "
            f"the {num_features}-feature architecture requires {expected}"
        )
    offset = 0
    with torch.no_grad():
        for name in names:
            target = state[name]
            count = target.numel()
            values = np.asarray(flat[offset : offset + count], dtype=np.float32).reshape(
                tuple(target.shape)
            )
            target.copy_(torch.from_numpy(values))
            offset += count
    model.load_state_dict(state)


def _fit(
    X,
    y,
    tr,
    va,
    num_features,
    epochs,
    seed,
    sample_weights=None,
    validation_groups=None,
    validation_real_mask=None,
    initial_weights_path=None,
    learning_rate=2e-3,
):
    """Train a MoE and retain the best policy-safe validation checkpoint."""
    import torch

    # Seed the CPU generator directly. `torch.manual_seed` also probes CUDA and
    # emits a driver warning even though this compact trainer is CPU-resident.
    torch.random.default_generator.manual_seed(seed)
    Xt = torch.from_numpy(X[tr])
    yt = torch.from_numpy(y[tr])
    Xv = torch.from_numpy(X[va])
    train_sample_weights = (
        torch.from_numpy(np.asarray(sample_weights[tr], dtype=np.float32))
        if sample_weights is not None
        else None
    )

    model = build_model(num_features)
    if initial_weights_path:
        load_serialized_weights(model, initial_weights_path, num_features)
    opt = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-5)

    # class balance weight (corpus is ~balanced but be robust)
    pos_w = float((y[tr] == 0).sum()) / max(1.0, float((y[tr] == 1).sum()))

    model.eval()
    with torch.no_grad():
        initial_probs = model(Xv).numpy()
    initial_groups = None if validation_groups is None else validation_groups[va]
    initial_real_mask = None if validation_real_mask is None else validation_real_mask[va]
    initial_real_floors = None
    if (
        initial_weights_path
        and initial_real_mask is not None
        and np.asarray(initial_real_mask, dtype=bool).any()
    ):
        initial_real_f1, initial_real_precision, _ = prf(
            initial_probs[initial_real_mask],
            y[va][initial_real_mask],
            0.5,
        )
        initial_real_floors = (
            initial_real_f1 - 1e-12,
            initial_real_precision - 1e-12,
        )
    best_key = validation_selection_key(
        initial_probs,
        y[va],
        initial_groups,
        initial_real_mask,
        initial_real_floors,
    )
    best_state = {key: value.detach().clone() for key, value in model.state_dict().items()}
    batch = 512
    for _epoch in range(epochs):
        model.train()
        perm = torch.randperm(len(tr))
        for b in range(0, len(tr), batch):
            sel = perm[b : b + batch]
            xb, yb = Xt[sel], yt[sel]
            p = model(xb).clamp(1e-6, 1 - 1e-6)
            w = torch.where(yb > 0.5, torch.tensor(pos_w), torch.tensor(1.0))
            if train_sample_weights is not None:
                w = w * train_sample_weights[sel]
            loss = torch.nn.functional.binary_cross_entropy(p, yb, weight=w)
            opt.zero_grad()
            loss.backward()
            opt.step()

        model.eval()
        with torch.no_grad():
            pv = model(Xv).numpy()
        groups = None if validation_groups is None else validation_groups[va]
        real_mask = None if validation_real_mask is None else validation_real_mask[va]
        key = validation_selection_key(
            pv,
            y[va],
            groups,
            real_mask,
            initial_real_floors,
        )
        if best_key is None or key > best_key:
            best_key = key
            best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}

    model.load_state_dict(best_state)
    model.eval()
    return model


def train(X, y, num_features, epochs, seed, kinds):
    """Synthetic-only training: random 85/15 split, report on the held-out 15%.
    Unchanged behaviour, the blended real-distribution path is `train_blended`."""
    import torch

    rng = np.random.default_rng(seed)
    n = len(y)
    idx = rng.permutation(n)
    split = int(n * 0.85)
    tr, va = idx[:split], idx[split:]
    model = _fit(X, y, tr, va, num_features, epochs, seed)
    with torch.no_grad():
        pv = model(torch.from_numpy(X[va])).numpy()
    return model, report(pv, y[va], [kinds[i] for i in va])


def load_real_corpus(path, num_features):
    """Load harvested real records.

    Returns (X, y, classes, detectors, files, calibration identities); `files`
    drives the no-leakage grouped split, while the exact secret-free identities
    condition held-out calibration.
    """
    kp, sk, tk, pk = config_lists.DEFAULT_LISTS
    records, y, classes, detectors, files, identities = [], [], [], [], [], []
    with open(path) as fh:
        for line_no, line in enumerate(fh, start=1):
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            records.append(rec)
            y.append(float(rec["label"]))
            classes.append(_required_corpus_field(path, line_no, rec, "class"))
            detector_id = _required_corpus_field(path, line_no, rec, "detector_id")
            channel = _required_corpus_field(path, line_no, rec, "candidate_channel")
            detector_policy.validate_candidate_channel(detector_id, channel)
            detectors.append(detector_id)
            files.append(_required_corpus_field(path, line_no, rec, "source_file"))
            identities.append(calibration_identity(path, line_no, rec))
    X = rust_features.compute_feature_matrix(records, (kp, sk, tk, pk), num_features)
    return X, np.asarray(y, dtype=np.float32), classes, detectors, files, identities


def _required_corpus_field(path, line_no, record, field):
    value = record.get(field)
    if isinstance(value, str) and value.strip():
        return value
    raise ValueError(
        f"{path}:{line_no}: corpus record missing required `{field}`; "
        "regenerate it with the owning corpus or harvest command"
    )


def _group_split(files, seed, fracs=(0.70, 0.15, 0.15)):
    """Partition record indices into (train, val, test) by GROUPING on file so a
    file's records never span splits, the only honest way to measure
    generalisation to unseen real files (a random split would leak a repo's
    secrets across train and test)."""
    rng = np.random.default_rng(seed)
    uniq = sorted(set(files))
    rng.shuffle(uniq)
    # Contract fixtures (source_file="contract:<det>") are a FIXED known-positive
    # set the scanner MUST catch, the standalone contract gate tests the full suite, so
    # they are a memorization requirement, NOT a generalization target. They
    # always train and never enter the held-out; only real-distribution
    # (CredData/homefield) files are split, keeping the held-out recall gate an
    # honest unseen-file generalization measure. No-op when no contracts present.
    contract_f = {f for f in uniq if f.startswith("contract:")}
    splittable = [f for f in uniq if f not in contract_f]
    n = len(splittable)
    a = int(n * fracs[0])
    b = a + int(n * fracs[1])
    train_f = set(splittable[:a]) | contract_f
    val_f, test_f = set(splittable[a:b]), set(splittable[b:])
    tr = np.array([i for i, f in enumerate(files) if f in train_f], dtype=np.int64)
    va = np.array([i for i, f in enumerate(files) if f in val_f], dtype=np.int64)
    te = np.array([i for i, f in enumerate(files) if f in test_f], dtype=np.int64)
    return tr, va, te


def per_class_eval(probs, labels, kinds, thr=0.5, floor=REAL_RECALL_FLOOR):
    """Per-secret-class held-out metrics for the shipped retrain gate."""
    out = {}
    normalized = [k or "unknown" for k in kinds]
    for kind in sorted(set(normalized)):
        idx = [i for i, k in enumerate(normalized) if k == kind]
        if not idx:
            continue
        k_probs = probs[idx]
        k_labels = labels[idx]
        pred = (k_probs >= thr).astype(np.float32)
        pos_mask = k_labels >= 0.5
        neg_mask = ~pos_mask
        tp = int(((pred == 1) & pos_mask).sum())
        fp = int(((pred == 1) & neg_mask).sum())
        fn = int(((pred == 0) & pos_mask).sum())
        prec = tp / (tp + fp) if tp + fp else 0.0
        rec = tp / (tp + fn) if tp + fn else 0.0
        f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
        pos_probs = k_probs[pos_mask]
        floor_recall = (
            float(np.mean((pos_probs >= floor).astype(np.float32)))
            if len(pos_probs)
            else None
        )
        out[kind] = {
            "n_test": int(len(idx)),
            "n_pos": int(pos_mask.sum()),
            "n_neg": int(neg_mask.sum()),
            "tp": tp,
            "fp": fp,
            "fn": fn,
            "precision": round(prec, 4),
            "recall": round(rec, 4),
            "f1": round(f1, 4),
            "recall_at_0_40_floor": round(floor_recall, 4)
            if floor_recall is not None
            else None,
        }
    return out


def calibration_identity(path, line_no, record):
    """Return the secret-free exact calibration key for one named-pattern row."""
    source_file = record.get("source_file")
    if isinstance(source_file, str) and source_file.startswith("contract:"):
        return None
    channel = _required_corpus_field(
        path, line_no, record, "candidate_channel"
    )
    if channel != "pattern":
        return None
    pattern_index = record.get("pattern_index")
    if (
        isinstance(pattern_index, bool)
        or not isinstance(pattern_index, int)
        or pattern_index < 0
        or pattern_index > 0xFFFFFFFF
    ):
        raise ValueError(
            f"{path}:{line_no}: corpus record has invalid `pattern_index`; "
            "regenerate it from scanner candidate provenance"
        )
    detector_digest = _required_corpus_field(
        path, line_no, record, "detector_digest"
    )
    if (
        len(detector_digest) != 16
        or any(ch not in "0123456789abcdef" for ch in detector_digest)
    ):
        raise ValueError(
            f"{path}:{line_no}: `detector_digest` must be 16 lowercase hex digits"
        )
    detector_id = _required_corpus_field(path, line_no, record, "detector_id")
    if not valid_detector_slug(detector_id):
        raise ValueError(
            f"{path}:{line_no}: detector_id must be a bounded lowercase detector slug"
        )
    source_role = _required_corpus_field(path, line_no, record, "source_role")
    context_class = _required_corpus_field(path, line_no, record, "context_class")
    if source_role not in PATTERN_CALIBRATION_SOURCE_ROLES:
        raise ValueError(
            f"{path}:{line_no}: unknown calibration source_role {source_role!r}"
        )
    if context_class not in PATTERN_CALIBRATION_CONTEXT_CLASSES:
        raise ValueError(
            f"{path}:{line_no}: unknown calibration context_class {context_class!r}"
        )
    return {
        "detector_id": detector_id,
        "pattern_index": pattern_index,
        "candidate_channel": channel,
        "source_role": source_role,
        "context_class": context_class,
        "detector_digest": detector_digest,
    }


def expected_calibration_error(probs, labels, bins=10):
    """Return deterministic equal-width ECE over a bounded held-out row set."""
    probs = np.asarray(probs, dtype=np.float64)
    labels = np.asarray(labels, dtype=np.float64)
    if len(probs) != len(labels) or bins <= 0:
        raise ValueError("ECE requires equal non-empty dimensions and positive bins")
    if len(probs) == 0:
        return 0.0
    if (
        not np.isfinite(probs).all()
        or not np.isfinite(labels).all()
        or ((probs < 0.0) | (probs > 1.0)).any()
        or ((labels != 0.0) & (labels != 1.0)).any()
    ):
        raise ValueError("ECE inputs must be finite probabilities and binary labels")
    bucket = np.minimum((probs * bins).astype(np.int64), bins - 1)
    ece = 0.0
    for index in range(bins):
        selected = bucket == index
        support = int(selected.sum())
        if support:
            ece += (
                support
                / len(probs)
                * abs(float(probs[selected].mean() - labels[selected].mean()))
            )
    return ece


def validate_calibration_floors(floors):
    required = set(PATTERN_CALIBRATION_DEFAULT_FLOORS)
    if set(floors) != required:
        raise ValueError(
            f"calibration floors must contain exactly {sorted(required)!r}"
        )
    values = {key: float(value) for key, value in floors.items()}
    if (
        not all(math.isfinite(value) for value in values.values())
        or values["blocking_score"] != REAL_RECALL_FLOOR
        or values["minimum_positive_support"] < 2
        or values["minimum_negative_support"] < 2
        or values["minimum_recall"] < 1.0
        or values["maximum_brier_score"] > 0.25
        or values["maximum_ece"] > 0.1
    ):
        raise ValueError("calibration artifact weakens the serving floors")


def pattern_calibration_entries(
    float_probs,
    quantized_probs,
    labels,
    identities,
    floors=None,
):
    """Build conservative per-key metrics after exact float/quantized verdict parity."""
    floors = dict(PATTERN_CALIBRATION_DEFAULT_FLOORS if floors is None else floors)
    validate_calibration_floors(floors)
    float_probs = np.asarray(float_probs, dtype=np.float64)
    quantized_probs = np.asarray(quantized_probs, dtype=np.float64)
    labels = np.asarray(labels, dtype=np.float64)
    if not (
        len(float_probs)
        == len(quantized_probs)
        == len(labels)
        == len(identities)
    ):
        raise ValueError("calibration probabilities, labels, and identities differ in length")
    blocking = float(floors["blocking_score"])
    groups = {}
    for index, identity in enumerate(identities):
        if identity is None:
            continue
        if (
            not valid_detector_slug(identity.get("detector_id"))
            or identity.get("candidate_channel") != "pattern"
            or identity.get("source_role") not in PATTERN_CALIBRATION_SOURCE_ROLES
            or identity.get("context_class") not in PATTERN_CALIBRATION_CONTEXT_CLASSES
            or isinstance(identity.get("pattern_index"), bool)
            or not isinstance(identity.get("pattern_index"), int)
            or not 0 <= identity["pattern_index"] <= 0xFFFFFFFF
        ):
            raise ValueError("calibration identity is not an exact bounded scanner key")
        key = (
            identity["detector_id"],
            identity["pattern_index"],
            identity["candidate_channel"],
            identity["source_role"],
            identity["context_class"],
        )
        groups.setdefault(key, []).append(index)
    entries = []
    for key in sorted(groups):
        selected = np.asarray(groups[key], dtype=np.int64)
        fp = float_probs[selected]
        qp = quantized_probs[selected]
        truth = labels[selected]
        for threshold in (0.5, blocking):
            if not np.array_equal(fp >= threshold, qp >= threshold):
                raise ValueError(
                    "float/quantized verdict parity failed for calibration key "
                    f"{key!r} at threshold {threshold}"
                )
        positive = truth >= 0.5
        negative = ~positive
        pred = fp >= 0.5
        tp = int((pred & positive).sum())
        fp_count = int((pred & negative).sum())
        fn = int(((~pred) & positive).sum())
        precision = tp / (tp + fp_count) if tp + fp_count else 0.0
        recall = tp / (tp + fn) if tp + fn else 0.0
        f1 = (
            2.0 * precision * recall / (precision + recall)
            if precision + recall
            else 0.0
        )
        positive_support = int(positive.sum())
        blocking_recall = (
            min(
                float(np.mean(fp[positive] >= blocking)),
                float(np.mean(qp[positive] >= blocking)),
            )
            if positive_support
            else 0.0
        )
        metrics = {
            "f1": f1,
            "precision": precision,
            "recall": recall,
            "recall_at_blocking_floor": blocking_recall,
            "brier_score": max(
                float(np.mean((fp - truth) ** 2)),
                float(np.mean((qp - truth) ** 2)),
            ),
            "ece": max(
                expected_calibration_error(fp, truth),
                expected_calibration_error(qp, truth),
            ),
            "positive_support": positive_support,
            "negative_support": int(negative.sum()),
        }
        entries.append(
            {
                "detector_id": key[0],
                "pattern_index": key[1],
                "candidate_channel": key[2],
                "source_role": key[3],
                "context_class": key[4],
                "metrics": metrics,
            }
        )
    return entries


def build_pattern_calibration_artifact(
    model_version,
    detector_digest,
    float_probs,
    quantized_probs,
    labels,
    identities,
    floors=None,
):
    """Build the persisted artifact without candidate text or source context."""
    if not valid_model_version(model_version):
        raise ValueError(
            "calibration model_version must use moe-v1- plus 16 lowercase hex digits"
        )
    floors = dict(PATTERN_CALIBRATION_DEFAULT_FLOORS if floors is None else floors)
    entries = pattern_calibration_entries(
        float_probs,
        quantized_probs,
        labels,
        identities,
        floors,
    )
    if entries and (
        not isinstance(detector_digest, str)
        or len(detector_digest) != 16
        or any(ch not in "0123456789abcdef" for ch in detector_digest)
    ):
        raise ValueError("populated calibration artifact requires a 16-digit detector digest")
    return {
        "schema_version": PATTERN_CALIBRATION_SCHEMA_VERSION,
        "identity_schema": PATTERN_CALIBRATION_IDENTITY_SCHEMA,
        "model_version": model_version,
        "detector_digest": detector_digest if entries else None,
        "floors": floors,
        "entries": entries,
    }


def serialize_pattern_calibration_artifact(artifact):
    return (json.dumps(artifact, indent=2, sort_keys=True) + "\n").encode("utf-8")


def pattern_calibration_model_card_summary(artifact):
    if artifact.get("schema_version") != PATTERN_CALIBRATION_SCHEMA_VERSION:
        raise ValueError("model-card calibration summary requires the current schema")
    if artifact.get("identity_schema") != PATTERN_CALIBRATION_IDENTITY_SCHEMA:
        raise ValueError("model-card calibration summary has a stale identity schema")
    if not valid_model_version(artifact.get("model_version")):
        raise ValueError("model-card calibration summary has an invalid model version")
    floors = artifact.get("floors")
    if not isinstance(floors, dict):
        raise ValueError("model-card calibration summary requires floors")
    validate_calibration_floors(floors)
    entries = artifact.get("entries")
    if not isinstance(entries, list):
        raise ValueError("model-card calibration summary requires entries")
    detector_digest = artifact.get("detector_digest")
    if entries:
        if (
            not isinstance(detector_digest, str)
            or len(detector_digest) != 16
            or any(ch not in "0123456789abcdef" for ch in detector_digest)
        ):
            raise ValueError(
                "populated model-card calibration summary requires detector digest"
            )
    elif detector_digest is not None:
        raise ValueError(
            "empty model-card calibration summary requires null detector digest"
        )
    positive_support = 0
    negative_support = 0
    eligible_entries = 0
    recalls = []
    blocking_recalls = []
    brier_scores = []
    eces = []
    expected_entry_fields = {
        "detector_id",
        "pattern_index",
        "candidate_channel",
        "source_role",
        "context_class",
        "metrics",
    }
    expected_metric_fields = {
        "f1",
        "precision",
        "recall",
        "recall_at_blocking_floor",
        "brier_score",
        "ece",
        "positive_support",
        "negative_support",
    }
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != expected_entry_fields:
            raise ValueError("model-card calibration entry has an invalid shape")
        if (
            not valid_detector_slug(entry["detector_id"])
            or isinstance(entry["pattern_index"], bool)
            or not isinstance(entry["pattern_index"], int)
            or not 0 <= entry["pattern_index"] <= 0xFFFFFFFF
            or entry["candidate_channel"] != "pattern"
            or entry["source_role"] not in PATTERN_CALIBRATION_SOURCE_ROLES
            or entry["context_class"] not in PATTERN_CALIBRATION_CONTEXT_CLASSES
        ):
            raise ValueError("model-card calibration entry has an invalid identity")
        metrics = entry["metrics"]
        if not isinstance(metrics, dict) or set(metrics) != expected_metric_fields:
            raise ValueError("model-card calibration entry has invalid metrics")
        for support_field in ("positive_support", "negative_support"):
            support = metrics[support_field]
            if isinstance(support, bool) or not isinstance(support, int) or support < 0:
                raise ValueError("model-card calibration support must be nonnegative integers")
        for metric_field in expected_metric_fields - {
            "positive_support",
            "negative_support",
        }:
            value = metrics[metric_field]
            if (
                isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not math.isfinite(value)
                or not 0.0 <= value <= 1.0
            ):
                raise ValueError(
                    "model-card calibration quality metrics must be probabilities"
                )
        positive_support += int(metrics["positive_support"])
        negative_support += int(metrics["negative_support"])
        recalls.append(float(metrics["recall"]))
        blocking_recalls.append(float(metrics["recall_at_blocking_floor"]))
        brier_scores.append(float(metrics["brier_score"]))
        eces.append(float(metrics["ece"]))
        eligible_entries += int(
            metrics["positive_support"] >= floors["minimum_positive_support"]
            and metrics["negative_support"] >= floors["minimum_negative_support"]
            and metrics["recall"] >= floors["minimum_recall"]
            and metrics["recall_at_blocking_floor"] >= floors["minimum_recall"]
            and metrics["brier_score"] <= floors["maximum_brier_score"]
            and metrics["ece"] <= floors["maximum_ece"]
        )
    return {
        "artifact_sha256": hashlib.sha256(
            serialize_pattern_calibration_artifact(artifact)
        ).hexdigest(),
        "schema_version": artifact["schema_version"],
        "identity_schema": artifact["identity_schema"],
        "model_version": artifact["model_version"],
        "detector_digest": artifact.get("detector_digest"),
        "status": "abstaining" if not entries else "calibrated",
        "floors": dict(floors),
        "entry_count": len(entries),
        "eligible_entry_count": eligible_entries,
        "aggregate_metrics": {
            "positive_support": positive_support,
            "negative_support": negative_support,
            "minimum_recall": min(recalls) if recalls else None,
            "minimum_recall_at_blocking_floor": (
                min(blocking_recalls) if blocking_recalls else None
            ),
            "maximum_brier_score": max(brier_scores) if brier_scores else None,
            "maximum_ece": max(eces) if eces else None,
        },
    }


def validation_selection_key(
    probs,
    labels,
    groups=None,
    real_mask=None,
    minimum_real_metrics=None,
):
    """Choose checkpoints by the same recall constraints shipping enforces.

    Groups are derived only from detector policy plus the real validation split;
    the held-out test split remains untouched. Fewer recall-sensitive classes
    below the report floor wins first, then the worst class recall, then
    aggregate F1. Synthetic-only training retains aggregate-F1 selection.
    """
    f1, _, _ = prf(probs, labels, 0.5)
    if groups is None:
        return (f1,)
    recalls = []
    normalized = np.asarray([group or "" for group in groups], dtype=object)
    labels = np.asarray(labels)
    probs = np.asarray(probs)
    for group in sorted(set(normalized) - {""}):
        positive = (normalized == group) & (labels >= 0.5)
        if int(positive.sum()) < 2:
            continue
        recalls.append(float(np.mean(probs[positive] >= REAL_RECALL_FLOOR)))
    failing = sum(recall < RECALL_SENSITIVE_CLASS_FLOOR for recall in recalls)
    minimum = min(recalls, default=1.0)
    if real_mask is None or not np.asarray(real_mask, dtype=bool).any():
        return (-failing, minimum, f1)
    real_mask = np.asarray(real_mask, dtype=bool)
    real_f1, real_precision, _ = prf(probs[real_mask], labels[real_mask], 0.5)
    minimum_real_f1, minimum_real_precision = (
        minimum_real_metrics
        if minimum_real_metrics is not None
        else (REAL_F1_FLOOR, REAL_PRECISION_FLOOR)
    )
    eligible = int(
        real_f1 >= minimum_real_f1 and real_precision >= minimum_real_precision
    )
    return (eligible, -failing, minimum, real_f1, real_precision, f1)


def real_eval(probs, labels, classes, detectors=None, thr=0.5):
    """Held-out real-distribution metrics. The headline is recall on real
    positives clearing the 0.40 report floor, the number the synthetic-only
    model failed (it scored real ambiguous secrets ~0.02)."""
    f1, prec, rec = prf(probs, labels, thr)
    pos = [float(probs[i]) for i, l in enumerate(labels) if l >= 0.5]
    neg = [float(probs[i]) for i, l in enumerate(labels) if l < 0.5]
    floor_recall = (
        float(np.mean([1.0 if p >= REAL_RECALL_FLOOR else 0.0 for p in pos]))
        if pos
        else float("nan")
    )
    out = {
        "real_f1": round(f1, 4),
        "real_precision": round(prec, 4),
        "real_recall": round(rec, 4),
        "n_test": int(len(labels)),
        "n_pos": len(pos),
        "n_neg": len(neg),
        "pos_mean_score": round(float(np.mean(pos)), 4) if pos else None,
        "neg_mean_score": round(float(np.mean(neg)), 4) if neg else None,
        "real_pos_recall_at_0.40_floor": round(floor_recall, 4),
        "per_class": per_class_eval(probs, labels, classes, thr, REAL_RECALL_FLOOR),
    }
    if detectors is not None:
        out["per_detector"] = per_class_eval(
            probs,
            labels,
            detectors,
            thr,
            REAL_RECALL_FLOOR,
        )
        sensitive = np.asarray(
            [detector_policy.model_can_reduce_recall(detector) for detector in detectors],
            dtype=bool,
        )
        out["per_recall_sensitive_class"] = per_class_eval(
            probs[sensitive],
            labels[sensitive],
            [kind for kind, keep in zip(classes, sensitive) if keep],
            thr,
            REAL_RECALL_FLOOR,
        )
    return out


def real_metric_summary(metrics: dict) -> dict:
    """Compact terminal summary; the model card retains the complete tables."""
    headline = {
        key: metrics.get(key)
        for key in (
            "real_f1",
            "real_precision",
            "real_recall",
            "real_pos_recall_at_0.40_floor",
            "n_test",
            "n_pos",
            "n_neg",
        )
    }
    per_detector = metrics.get("per_detector", {})
    headline["recall_sensitive_detectors"] = {
        detector_id: metric.get("recall_at_0_40_floor")
        for detector_id, metric in sorted(per_detector.items())
        if isinstance(metric, dict)
        and int(metric.get("n_pos") or 0) > 0
        and detector_policy.model_can_reduce_recall(detector_id)
    }
    headline["zero_recall_detectors"] = [
        detector_id
        for detector_id, metric in sorted(per_detector.items())
        if isinstance(metric, dict)
        and int(metric.get("n_pos") or 0) > 0
        and metric.get("recall_at_0_40_floor") == 0.0
    ]
    return headline


def train_blended(
    Xs,
    ys,
    kinds_s,
    detectors_s,
    Xr,
    yr,
    classes_r,
    detectors_r,
    files_r,
    num_features,
    epochs,
    seed,
    max_detector_positive_multiplier,
    max_recall_sensitive_class_multiplier,
    initial_weights_path=None,
    learning_rate=2e-3,
):
    """Train on synthetic (breadth) + real-TRAIN, select on synthetic-val +
    real-val, and report on a real-TEST held out by file (no leakage). Returns
    (model, synthetic_val_metrics, real_heldout_metrics)."""
    import torch

    rng = np.random.default_rng(seed)
    si = rng.permutation(len(ys))
    ssplit = int(len(ys) * 0.85)
    s_tr, s_va = si[:ssplit], si[ssplit:]
    r_tr, r_va, r_te = _group_split(files_r, seed)

    X = np.concatenate([Xs, Xr])
    y = np.concatenate([ys, yr])
    off = len(ys)
    tr = np.concatenate([s_tr, r_tr + off])
    va = np.concatenate([s_va, r_va + off])  # model selection (syn + real val)

    sample_weights = detector_balanced_sample_weights(
        y,
        tr,
        [*detectors_s, *detectors_r],
        max_detector_positive_multiplier,
    )
    sample_weights *= recall_sensitive_class_sample_weights(
        len(y),
        off,
        yr,
        classes_r,
        detectors_r,
        r_tr,
        max_recall_sensitive_class_multiplier,
    )

    validation_groups = np.asarray(
        [""] * len(ys)
        + [
            (kind or "unknown")
            if detector_policy.model_can_reduce_recall(detector)
            else ""
            for kind, detector in zip(classes_r, detectors_r)
        ],
        dtype=object,
    )
    validation_real_mask = np.asarray(
        [False] * len(ys) + [True] * len(yr),
        dtype=bool,
    )

    model = _fit(
        X,
        y,
        tr,
        va,
        num_features,
        epochs,
        seed,
        sample_weights,
        validation_groups,
        validation_real_mask,
        initial_weights_path,
        learning_rate,
    )
    with torch.no_grad():
        syn_val_p = model(torch.from_numpy(Xs[s_va])).numpy()
        real_te_p = model(torch.from_numpy(Xr[r_te])).numpy() if len(r_te) else np.array([])
    syn_metrics = report(syn_val_p, ys[s_va], [kinds_s[i] for i in s_va])
    real_metrics = (
        real_eval(
            real_te_p,
            yr[r_te],
            [classes_r[i] for i in r_te],
            [detectors_r[i] for i in r_te],
        )
        if len(r_te)
        else {"note": "no real test split"}
    )
    return model, syn_metrics, real_metrics


def detector_balanced_sample_weights(
    combined_labels,
    combined_train_indices,
    combined_detectors,
    max_multiplier,
):
    """Balance positive loss inside each detector without held-out data.

    Global class weighting cannot protect a detector whose own candidate stream
    is much more negative-heavy than the aggregate. This multiplier brings each
    positive-bearing detector toward its own train-split class balance and
    positive support, capped so a tiny family cannot dominate the model.
    """
    if not math.isfinite(max_multiplier) or max_multiplier < 1.0:
        raise ValueError("max detector positive multiplier must be finite and >= 1.0")
    labels = np.asarray(combined_labels)
    train_labels = labels[combined_train_indices]
    global_positive_weight = float((train_labels == 0).sum()) / max(
        1.0, float((train_labels == 1).sum())
    )
    if len(combined_detectors) != len(labels):
        raise ValueError("combined detector identities must match combined labels")
    counts: dict[str, list[int]] = {}
    for index in combined_train_indices:
        detector = combined_detectors[index]
        if not detector_policy.model_can_reduce_recall(detector):
            continue
        pair = counts.setdefault(detector, [0, 0])
        pair[1 if labels[index] > 0.5 else 0] += 1

    weights = np.ones(len(labels), dtype=np.float32)
    positive_support_target = max((pair[1] for pair in counts.values()), default=1)
    for index in combined_train_indices:
        if labels[index] <= 0.5:
            continue
        detector = combined_detectors[index]
        if detector not in counts:
            continue
        negatives, positives = counts[detector]
        if positives == 0:
            continue
        detector_positive_weight = negatives / positives if negatives else 0.0
        balance_multiplier = max(1.0, detector_positive_weight / global_positive_weight)
        support_multiplier = positive_support_target / positives
        weights[index] = min(
            max_multiplier,
            max(balance_multiplier, support_multiplier),
        )
    return weights


def recall_sensitive_class_sample_weights(
    combined_length,
    real_offset,
    real_labels,
    real_classes,
    real_detectors,
    real_train_indices,
    max_multiplier,
):
    """Balance positive recall-sensitive classes using train rows only."""
    if not math.isfinite(max_multiplier) or max_multiplier < 1.0:
        raise ValueError(
            "max recall-sensitive class multiplier must be finite and >= 1.0"
        )
    counts: dict[tuple[str, str], int] = {}
    for index in real_train_indices:
        detector = real_detectors[index]
        if real_labels[index] <= 0.5 or not detector_policy.model_can_reduce_recall(detector):
            continue
        key = (detector, real_classes[index] or "unknown")
        counts[key] = counts.get(key, 0) + 1

    target = max(counts.values(), default=1)
    weights = np.ones(combined_length, dtype=np.float32)
    for index in real_train_indices:
        detector = real_detectors[index]
        if real_labels[index] <= 0.5 or not detector_policy.model_can_reduce_recall(detector):
            continue
        count = counts[(detector, real_classes[index] or "unknown")]
        weights[real_offset + index] = min(max_multiplier, target / count)
    return weights


def prf(probs, labels, thr):
    pred = (probs >= thr).astype(np.float32)
    tp = float(((pred == 1) & (labels == 1)).sum())
    fp = float(((pred == 1) & (labels == 0)).sum())
    fn = float(((pred == 0) & (labels == 1)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
    return f1, prec, rec


def report(probs, labels, kinds):
    f1, prec, rec = prf(probs, labels, 0.5)
    # base64-binary FP behaviour: mean score on those negatives (want it LOW)
    bin_scores = [probs[i] for i, k in enumerate(kinds) if k == "base64-binary"]
    bin_mean = float(np.mean(bin_scores)) if bin_scores else float("nan")
    bin_flagged = (
        float(np.mean([1.0 if s >= 0.5 else 0.0 for s in bin_scores]))
        if bin_scores
        else float("nan")
    )
    return {
        "f1": f1,
        "precision": prec,
        "recall": rec,
        "n_val": int(len(labels)),
        "base64_binary_mean_score": bin_mean,
        "base64_binary_flag_rate": bin_flagged,
        "n_base64_binary_val": len(bin_scores),
    }


def probe(model, num_features: int):
    """Score canonical probe strings through the trained model so regressions
    on known cases (the Rust ml_scorer unit tests) surface here, before the
    slow Rust rebuild. Mirrors the assertions in tests/unit/ml_scorer.rs."""
    import base64
    import torch

    kp, sk, tk, pk = config_lists.DEFAULT_LISTS
    png = base64.b64encode(b"\x89PNG\r\n\x1a\n" + bytes(range(24))).decode()
    # Fragment-assembled so this source file carries no full token literal.
    ghp = "gh" + "p_" + "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij"
    cases = [
        ("real ghp PAT", ghp, f"GITHUB_TOKEN={ghp}", "high", "github-classic-pat", "pattern"),
        ("md5 hash", "d41d8cd98f00b204e9800998ecf8427e",
         "checksum = d41d8cd98f00b204e9800998ecf8427e", "low", "generic-secret", "entropy"),
        ("sha256 digest", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
         "sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "low", "generic-secret", "entropy"),
        ("real hex key", "9f8c2a1b4d6e7f80112233445566778899aabbccddeeff00",
         "encryption_key = 9f8c2a1b4d6e7f80112233445566778899aabbccddeeff00", "high", "generic-secret", "pattern"),
        ("placeholder", "YOUR_API_KEY_HERE", "api_key = YOUR_API_KEY_HERE", "low", "generic-api-key", "pattern"),
        ("base64 PNG", png, f"avatar = {png}", "low", "generic-secret", "entropy"),
        # precision probes: bare/prose high-entropy tokens with NO anchor MUST
        # read low (these were the mirror false positives).
        ("bare token", "Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2",
         "value = Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2", "low", "generic-secret", "entropy"),
        ("prose token", "aZ4kP9qR2sT7vW1xY6bC3dE8fG0hJ5mN",
         "Session opened with handle aZ4kP9qR2sT7vW1xY6bC3dE8fG0hJ5mN. See docs.", "low", "generic-secret", "entropy"),
        # recall probe: same shape WITH a secret keyword MUST read high.
        ("anchored secret", "Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2",
         "api_key = Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2", "high", "generic-api-key", "pattern"),
    ]
    model.eval()
    out = {}
    records = [
        {
            "text": text,
            "context": ctx,
            "detector_id": detector_id,
            "candidate_channel": channel,
        }
        for _name, text, ctx, _want, detector_id, channel in cases
    ]
    vectors = rust_features.compute_feature_matrix(records, (kp, sk, tk, pk), num_features)
    with torch.no_grad():
        for (name, _text, _ctx, want, _detector_id, _channel), vec in zip(cases, vectors):
            s = float(model(torch.from_numpy(np.asarray(vec, dtype=np.float32)[None, :]))[0])
            out[name] = {"score": round(s, 3), "want": want}
    return out


def probe_gate_error(probes: dict, threshold: float = 0.5) -> str:
    """Reject a model that reverses a canonical positive/negative contract."""
    failures = []
    for name, result in probes.items():
        score = result.get("score")
        want = result.get("want")
        if not isinstance(score, (float, int)) or want not in {"high", "low"}:
            failures.append(f"{name}: malformed probe result {result!r}")
        elif want == "high" and score < threshold:
            failures.append(f"{name}: score {score:.3f} < {threshold:.3f}")
        elif want == "low" and score >= threshold:
            failures.append(f"{name}: score {score:.3f} >= {threshold:.3f}")
    if not failures:
        return ""
    return "REFUSING model: canonical probe contract failed: " + "; ".join(failures) + "\n"


def parameter_count(num_features: int) -> int:
    return (
        num_features * EXPERT_COUNT
        + EXPERT_COUNT
        + EXPERT_COUNT
        * (num_features * FC1 + FC1 + FC1 * FC2 + FC2 + FC2 + 1)
    )


def serialize(model, num_features: int) -> bytes:
    """Flatten the model into the exact little-endian f32 layout ml_weights.rs
    parses. Linear.weight is [out, in] row-major, which is precisely the
    `weights[out_idx*in + in_idx]` indexing the Rust forward pass uses."""
    sd = model.state_dict()
    buf = []

    def add(t):
        buf.append(np.asarray(t.detach().cpu().numpy(), dtype="<f4").ravel())

    add(sd["gate.weight"])  # [6, D]
    add(sd["gate.bias"])  # [6]
    for e in range(EXPERT_COUNT):
        add(sd[f"experts.{e}.fc1.weight"])  # [32, D]
        add(sd[f"experts.{e}.fc1.bias"])  # [32]
        add(sd[f"experts.{e}.fc2.weight"])  # [16, 32]
        add(sd[f"experts.{e}.fc2.bias"])  # [16]
        add(sd[f"experts.{e}.fc3.weight"])  # [1, 16]
        add(sd[f"experts.{e}.fc3.bias"])  # [1]

    flat = np.concatenate(buf)
    expected = parameter_count(num_features)
    assert flat.size == expected, f"layout size {flat.size} != expected {expected}"
    return flat.tobytes()

def serialize_quantized(blob: bytes, num_features: int) -> bytes:
    """Serialize the current model into the canonical signed Q7 wire format."""
    if num_features != rust_features.NUM_FEATURES:
        raise ValueError(
            "quantized serving requires the current "
            f"{rust_features.NUM_FEATURES}-feature schema, got {num_features}"
        )
    expected_bytes = parameter_count(num_features) * np.dtype("<f4").itemsize
    if len(blob) != expected_bytes:
        raise ValueError(
            f"quantized serving expected {expected_bytes} model bytes, got {len(blob)}"
        )
    flat = np.frombuffer(blob, dtype="<f4")
    if not np.isfinite(flat).all():
        raise ValueError("quantized serving cannot encode non-finite model parameters")
    scale = 1 << QUANTIZED_FRACTIONAL_BITS
    scaled = flat.astype(np.float64) * scale
    rounded = np.where(
        scaled >= 0.0,
        np.floor(scaled + 0.5),
        np.ceil(scaled - 0.5),
    )
    quantized = np.clip(rounded, -32768, 32767).astype("<i2")
    parameter_bound = int(np.max(np.abs(quantized.astype(np.int64))))
    dense_terms = max(num_features, FC1, FC2)
    maximum_dense_accumulator = (
        dense_terms * 32768 * parameter_bound
        + scale * parameter_bound
        + scale // 2
    )
    if maximum_dense_accumulator > np.iinfo(np.int32).max:
        raise ValueError(
            "quantized serving parameter magnitude "
            f"{parameter_bound} exceeds the VYRE i32 arithmetic bound"
        )
    payload = quantized.tobytes()
    payload_digest = hashlib.sha256(payload).digest()
    header = struct.pack(
        "<8s6HBBHI32s",
        b"KHQMOE\0\1",
        QUANTIZED_MODEL_FORMAT_VERSION,
        QUANTIZED_FEATURE_SCHEMA_VERSION,
        num_features,
        EXPERT_COUNT,
        FC1,
        FC2,
        QUANTIZED_FRACTIONAL_BITS,
        QUANTIZED_ROUNDING_TIES_AWAY,
        0,
        len(payload),
        payload_digest,
    )
    return header + payload


def weights_fnv1a64(blob: bytes) -> str:
    h = 0xCBF29CE484222325
    for b in blob:
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return f"{h:016x}"


def file_sha256(path: str | None) -> str | None:
    if not path:
        return None
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_model_card(
    blob: bytes,
    quantized_blob: bytes | None,
    feature_schema_digest: str | None,
    args,
    metrics,
    real_metrics=None,
    calibration_artifact=None,
) -> None:
    """Write model-card provenance beside the serialized weights.

    Shipped writes require real held-out metrics. A synthetic-only card would be
    stale the moment the binary is used on real corpora, so `--write` refuses
    that path before touching `weights.bin`.
    """
    if args.write and not real_metrics:
        raise SystemExit(
            "REFUSING to write: --write now requires --real-corpus so the shipped "
            "model_card.json carries leakage-free real held-out recall"
        )

    digest = weights_fnv1a64(blob)
    if calibration_artifact is None:
        calibration_artifact = build_pattern_calibration_artifact(
            f"moe-v1-{digest}", None, [], [], [], []
        )
    if calibration_artifact.get("model_version") != f"moe-v1-{digest}":
        raise ValueError("pattern calibration model version does not match weights")
    calibration_card = pattern_calibration_model_card_summary(calibration_artifact)
    real_card = dict(real_metrics) if real_metrics else {
        "note": "scratch training only; shipped writes require --real-corpus"
    }
    if "real_pos_recall_at_0.40_floor" in real_card:
        real_card["recall_at_0_40_floor"] = real_card["real_pos_recall_at_0.40_floor"]
    if args.write and not isinstance(real_card.get("recall_at_0_40_floor"), (float, int)):
        raise SystemExit(
            "REFUSING to write: real held-out metrics must include numeric "
            "recall_at_0_40_floor for model_card.json"
        )
    if args.write and not isinstance(real_card.get("per_class"), dict):
        raise SystemExit(
            "REFUSING to write: real held-out metrics must include per_class "
            "precision/recall for model_card.json"
        )
    if args.write and not isinstance(real_card.get("per_detector"), dict):
        raise SystemExit(
            "REFUSING to write: real held-out metrics must include per_detector "
            "precision/recall for model_card.json"
        )
    if args.write and not isinstance(real_card.get("per_recall_sensitive_class"), dict):
        raise SystemExit(
            "REFUSING to write: real held-out metrics must include "
            "per_recall_sensitive_class precision/recall for model_card.json"
        )
    if getattr(args, "real_corpus", None) and not isinstance(
        real_card.get("six_scanner_differential"),
        dict,
    ):
        raise SystemExit(
            "REFUSING retrain artifact: real-corpus model cards must include the "
            "full six-scanner per-class differential comparison"
        )
    card = {
        "schema_version": 3
        if isinstance(real_card.get("six_scanner_differential"), dict)
        else (2 if args.write else 1),
        "model_version": f"moe-v1-{digest}",
        "weights_fnv1a64": digest,
        "architecture": "moe-v1",
        "feature_count": args.features,
        "recorded_date": datetime.date.today().isoformat(),
        "trainer": "ml/train_classifier.py",
        "feature_source": "Rust dump_features serve path",
        "pattern_calibration": calibration_card,
        "training_inputs": {
            "synthetic": args.corpus,
            "synthetic_sha256": file_sha256(args.corpus),
            "real_distribution": args.real_corpus
            if args.real_corpus
            else "scratch training only; not shipped",
            "real_distribution_sha256": file_sha256(args.real_corpus),
        },
        "training_parameters": {
            "epochs": args.epochs,
            "seed": args.seed,
            "max_detector_positive_multiplier": args.max_detector_positive_multiplier,
            "max_recall_sensitive_class_multiplier": args.max_recall_sensitive_class_multiplier,
            "initial_weights": args.init_weights,
            "initial_weights_sha256": file_sha256(args.init_weights),
            "learning_rate": args.learning_rate,
        },
        "metrics": {
            "synthetic_heldout": metrics,
            "real_heldout": real_card,
        },
    }
    if quantized_blob is not None:
        if feature_schema_digest is None:
            raise ValueError("quantized model card requires a feature-schema digest")
        card["quantized_serving"] = {
            "artifact_sha256": hashlib.sha256(quantized_blob).hexdigest(),
            "feature_schema_sha256": feature_schema_digest,
            "feature_schema_version": QUANTIZED_FEATURE_SCHEMA_VERSION,
            "format_version": QUANTIZED_MODEL_FORMAT_VERSION,
            "fractional_bits": QUANTIZED_FRACTIONAL_BITS,
            "rounding": "nearest-ties-away-from-zero",
        }

    if args.write:
        path = args.model_card
        if os.path.exists(path):
            shutil.copy2(path, path + ".bak")
            sys.stderr.write(f"backed up existing model card -> {path}.bak\n")
    else:
        stem = os.path.splitext(os.path.basename(args.out))[0] or f"weights_{args.features}"
        path = os.path.join(os.path.dirname(args.corpus) or ".", f"{stem}.model_card.json")

    with open(path, "w", encoding="utf-8") as fh:
        json.dump(card, fh, indent=2, sort_keys=True)
        fh.write("\n")
    sys.stderr.write(f"wrote {path}\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default="ml/data/corpus.jsonl")
    ap.add_argument("--real-corpus", default=None,
                    help="harvested real-distribution JSONL to blend in (Stage 2); "
                         "enables the file-grouped real held-out eval")
    ap.add_argument("--out", default="crates/scanner/src/weights.bin")
    ap.add_argument("--quantized-out", default=CURRENT_QUANTIZED_MODEL,
                    help="quantized model artifact to update with --write")
    ap.add_argument("--model-card", default=CURRENT_MODEL_CARD,
                    help="model-card JSON to update with --write; must match weights.bin")
    ap.add_argument(
        "--pattern-calibration-out",
        default="crates/scanner/src/pattern_calibration.json",
        help="pattern-conditioned calibration artifact to update with --write",
    )
    ap.add_argument("--features", type=int, default=55, choices=[41, 42, 43, 51, 55])
    ap.add_argument("--epochs", type=int, default=60)
    ap.add_argument("--learning-rate", type=float, default=2e-3)
    ap.add_argument("--init-weights", default=None,
                    help="strictly load an existing compatible weights.bin before training")
    ap.add_argument("--seed", type=int, default=20260529)
    ap.add_argument("--compare", action="store_true", help="also train 41-feat baseline")
    ap.add_argument("--min-f1", type=float, default=0.85, help="refuse to write below this")
    ap.add_argument("--min-real-recall", type=float, default=0.50,
                    help="with --real-corpus, refuse to write if real held-out recall "
                         "at the 0.40 report floor drops below this (recall-first gate)")
    ap.add_argument("--min-real-f1", type=float, default=REAL_F1_FLOOR,
                    help="with --real-corpus, refuse a model below this held-out F1")
    ap.add_argument("--min-real-precision", type=float, default=REAL_PRECISION_FLOOR,
                    help="with --real-corpus, refuse a model below this held-out precision")
    ap.add_argument("--min-real-class-recall", type=float, default=0.50,
                    help="with --real-corpus, refuse to write if any positive-bearing "
                         "held-out class falls below this recall at the 0.40 report floor")
    ap.add_argument("--min-real-class-support", type=int, default=2,
                    help="minimum positive held-out examples for a class to enter the "
                         "per-class recall gate")
    ap.add_argument("--min-real-detector-recall", type=float, default=0.50,
                    help="with --real-corpus, refuse to write if any positive-bearing "
                         "held-out detector falls below this recall at the 0.40 floor")
    ap.add_argument("--min-real-detector-support", type=int, default=1,
                    help="minimum positive held-out examples required for every "
                         "recall-sensitive detector channel")
    ap.add_argument("--min-real-detector-negative-support", type=int, default=1,
                    help="minimum negative held-out examples required for every "
                         "recall-sensitive detector channel")
    ap.add_argument("--baseline-model-card", default=CURRENT_MODEL_CARD,
                    help="existing model card used to reject per-class and per-detector "
                         "real recall regressions during --write")
    ap.add_argument("--max-real-class-recall-drop", type=float, default=0.0,
                    help="allowed per-class recall@0.40 drop vs --baseline-model-card")
    ap.add_argument("--max-real-detector-recall-drop", type=float, default=0.0,
                    help="allowed per-detector recall@0.40 drop vs --baseline-model-card")
    ap.add_argument("--max-detector-positive-multiplier", type=float, default=16.0,
                    help="cap for train-split per-detector positive-loss balancing")
    ap.add_argument("--max-recall-sensitive-class-multiplier", type=float, default=1.0,
                    help="cap for train-split positive class balancing inside "
                         "recall-sensitive detectors")
    ap.add_argument("--differential-results", default=DEFAULT_DIFFERENTIAL_RESULTS,
                    help="benchmark RunResult directory used to compare every "
                         "positive held-out class against the full six-scanner "
                         "differential")
    ap.add_argument("--differential-corpus", default=DEFAULT_DIFFERENTIAL_CORPUS,
                    help="benchmark corpus name for the six-scanner differential")
    ap.add_argument("--require-differential", action="store_true",
                    help="refuse an artifact when the current six-scanner differential "
                         "is unavailable; normal writes record the unavailable status so "
                         "the freshly built candidate can be benchmarked")
    ap.add_argument("--verbose-metrics", action="store_true",
                    help="print full per-class/per-detector tables; they are always "
                         "retained in the model card")
    ap.add_argument("--write", action="store_true",
                    help="internal verified-loop write; direct invocation is refused")
    args = ap.parse_args()
    if not math.isfinite(args.learning_rate) or args.learning_rate <= 0.0:
        ap.error("--learning-rate must be finite and greater than zero")
    if args.epochs < 0 or (args.epochs == 0 and not args.init_weights):
        ap.error("--epochs must be positive, or zero only with --init-weights for evaluation")
    os.environ["CUDA_VISIBLE_DEVICES"] = ""
    sys.stderr.write("[TRAIN] device=cpu (runtime CPU/GPU inference parity is gated separately)\n")

    if args.write and os.environ.get("KEYHOG_VERIFIED_WRITE") != "1":
        sys.stderr.write(
            "REFUSING direct write: use `ml/retrain_loop.sh --write --verify` so "
            "the production scanner contracts and benchmark gates run\n"
        )
        return 2

    if args.real_corpus:
        # Stage 2: blend the real distribution in and measure on a file-grouped
        # real held-out (no leakage). The F1 gate still uses the SYNTHETIC val
        # (so breadth coverage cannot silently regress); the real held-out is
        # the recall number that matters and is reported alongside.
        Xs, ys, kinds_s, detectors_s = load_corpus(args.corpus, args.features)
        Xr, yr, classes_r, detectors_r, files_r, identities_r = load_real_corpus(
            args.real_corpus,
            args.features,
        )
        sys.stderr.write(
            f"[BLEND] synthetic={len(ys)} real={len(yr)} "
            f"(real pos={int(yr.sum())} neg={int((yr == 0).sum())}, "
            f"files={len(set(files_r))})\n"
        )
        model, metrics, real_metrics = train_blended(
            Xs,
            ys,
            kinds_s,
            detectors_s,
            Xr,
            yr,
            classes_r,
            detectors_r,
            files_r,
            args.features,
            args.epochs,
            args.seed,
            args.max_detector_positive_multiplier,
            args.max_recall_sensitive_class_multiplier,
            args.init_weights,
            args.learning_rate,
        )
        sys.stderr.write(f"[BLENDED syn-val {args.features}f] {json.dumps(metrics)}\n")
        shown_real_metrics = (
            real_metrics if args.verbose_metrics else real_metric_summary(real_metrics)
        )
        sys.stderr.write(f"[BLENDED real-held-out] {json.dumps(shown_real_metrics)}\n")
        probes = probe(model, args.features)
        sys.stderr.write(f"[PROBE] {json.dumps(probes)}\n")
        if probe_error := probe_gate_error(probes):
            sys.stderr.write(probe_error)
            return 1
        blob = serialize(model, args.features)
        sys.stderr.write(f"serialized {len(blob)} bytes ({len(blob) // 4} f32)\n")
        calibration_digests = {
            identity["detector_digest"]
            for identity in identities_r
            if identity is not None
        }
        if len(calibration_digests) > 1:
            sys.stderr.write(
                "REFUSING retrain artifact: real corpus mixes detector digests\n"
            )
            return 1
        if args.features == rust_features.NUM_FEATURES:
            import torch

            _, _, calibration_test_indices = _group_split(files_r, args.seed)
            quantized_candidate = serialize_quantized(blob, args.features)
            quantized_test_probs = rust_features.score_quantized_features(
                quantized_candidate,
                Xr[calibration_test_indices],
            )
            with torch.no_grad():
                float_test_probs = model(
                    torch.from_numpy(Xr[calibration_test_indices])
                ).numpy()
            calibration_artifact = build_pattern_calibration_artifact(
                f"moe-v1-{weights_fnv1a64(blob)}",
                next(iter(calibration_digests), None),
                float_test_probs,
                quantized_test_probs,
                yr[calibration_test_indices],
                [identities_r[index] for index in calibration_test_indices],
            )
        else:
            calibration_artifact = build_pattern_calibration_artifact(
                f"moe-v1-{weights_fnv1a64(blob)}",
                None,
                [],
                [],
                [],
                [],
            )
        if metrics["f1"] < args.min_f1:
            sys.stderr.write(
                f"REFUSING to write: synthetic val F1 {metrics['f1']:.4f} < floor {args.min_f1}\n"
            )
            return 1
        real_floor = real_metrics.get("real_pos_recall_at_0.40_floor")
        if isinstance(real_floor, float) and real_floor == real_floor and real_floor < args.min_real_recall:
            sys.stderr.write(
                f"REFUSING to write: real held-out recall@0.40 {real_floor:.4f} < floor "
                f"{args.min_real_recall} (a retrain must not regress real-distribution recall)\n"
            )
            return 1
        real_f1 = real_metrics.get("real_f1")
        if not isinstance(real_f1, (float, int)) or real_f1 < args.min_real_f1:
            shown = "missing" if not isinstance(real_f1, (float, int)) else f"{real_f1:.4f}"
            sys.stderr.write(
                f"REFUSING to write: real held-out F1 {shown} < floor "
                f"{args.min_real_f1:.4f}\n"
            )
            return 1
        real_precision = real_metrics.get("real_precision")
        if (
            not isinstance(real_precision, (float, int))
            or real_precision < args.min_real_precision
        ):
            shown = (
                "missing"
                if not isinstance(real_precision, (float, int))
                else f"{real_precision:.4f}"
            )
            sys.stderr.write(
                f"REFUSING to write: real held-out precision {shown} < floor "
                f"{args.min_real_precision:.4f}\n"
            )
            return 1
        class_gate_error = per_class_gate_error(real_metrics, args)
        if class_gate_error:
            sys.stderr.write(class_gate_error)
            return 1
        detector_gate_error = per_detector_gate_error(real_metrics, args)
        if detector_gate_error:
            sys.stderr.write(detector_gate_error)
            return 1
        real_metrics = dict(real_metrics)
        try:
            real_metrics["six_scanner_differential"] = (
                six_scanner_differential_comparison(real_metrics, args)
            )
        except ValueError as error:
            if args.require_differential:
                sys.stderr.write(f"REFUSING retrain artifact: {error}\n")
                return 1
            real_metrics["six_scanner_differential"] = {
                "status": "unavailable",
                "error": str(error),
            }
            sys.stderr.write(
                f"candidate artifact has no current six-scanner differential: {error}\n"
            )
        _write_weights(blob, args, metrics, real_metrics, calibration_artifact)
        return 0

    if args.write:
        sys.stderr.write(
            "REFUSING to write: --write requires --real-corpus so the shipped "
            "model_card.json carries leakage-free real held-out recall\n"
        )
        return 1

    if args.compare:
        for d in (41, 42):
            X, y, kinds, _detectors = load_corpus(args.corpus, d)
            _, m = train(X, y, d, args.epochs, args.seed, kinds)
            sys.stderr.write(f"[{d} features] {json.dumps(m)}\n")

    X, y, kinds, _detectors = load_corpus(args.corpus, args.features)
    model, metrics = train(X, y, args.features, args.epochs, args.seed, kinds)
    sys.stderr.write(f"[FINAL {args.features} features] {json.dumps(metrics)}\n")
    probes = probe(model, args.features)
    sys.stderr.write(f"[PROBE] {json.dumps(probes)}\n")
    if probe_error := probe_gate_error(probes):
        sys.stderr.write(probe_error)
        return 1

    blob = serialize(model, args.features)
    sys.stderr.write(f"serialized {len(blob)} bytes ({len(blob)//4} f32)\n")

    if metrics["f1"] < args.min_f1:
        sys.stderr.write(
            f"REFUSING to write: val F1 {metrics['f1']:.4f} < floor {args.min_f1}\n"
        )
        return 1

    _write_weights(blob, args, metrics)
    return 0


def _write_weights(
    blob: bytes,
    args,
    metrics,
    real_metrics=None,
    calibration_artifact=None,
) -> None:
    """Write the serialized weights: `--write` overwrites the crate's
    `weights.bin` (backing up the old one to `.bak`); otherwise a scratch file
    next to the corpus, never touching the shipped crate."""
    if args.features == rust_features.NUM_FEATURES:
        quantized_blob = serialize_quantized(blob, args.features)
        feature_schema_digest = rust_features.quantized_schema_digest()
    else:
        if args.write:
            raise SystemExit(
                "REFUSING to write: shipped quantized serving requires the current "
                f"{rust_features.NUM_FEATURES}-feature model"
            )
        quantized_blob = None
        feature_schema_digest = None
    if calibration_artifact is None:
        calibration_artifact = build_pattern_calibration_artifact(
            f"moe-v1-{weights_fnv1a64(blob)}",
            None,
            [],
            [],
            [],
            [],
        )
    if calibration_artifact.get("model_version") != (
        f"moe-v1-{weights_fnv1a64(blob)}"
    ):
        raise ValueError("pattern calibration model version does not match weights")
    pattern_calibration_model_card_summary(calibration_artifact)
    if args.write:
        real = real_metrics or {}
        recall = real.get("recall_at_0_40_floor", real.get("real_pos_recall_at_0.40_floor"))
        if not isinstance(recall, (float, int)):
            raise SystemExit(
                "REFUSING to write: real held-out metrics must include numeric "
                "recall_at_0_40_floor before weights.bin is touched"
            )
        if not isinstance(real.get("per_class"), dict):
            raise SystemExit(
                "REFUSING to write: real held-out metrics must include per_class "
                "precision/recall before weights.bin is touched"
            )
        if not isinstance(real.get("per_detector"), dict):
            raise SystemExit(
                "REFUSING to write: real held-out metrics must include per_detector "
                "precision/recall before weights.bin is touched"
            )
        if not isinstance(real.get("per_recall_sensitive_class"), dict):
            raise SystemExit(
                "REFUSING to write: real held-out metrics must include "
                "per_recall_sensitive_class precision/recall before weights.bin is touched"
            )
        if os.path.exists(args.out):
            shutil.copy2(args.out, args.out + ".bak")
            sys.stderr.write(f"backed up existing weights -> {args.out}.bak\n")
        with open(args.out, "wb") as fh:
            fh.write(blob)
        sys.stderr.write(f"wrote {args.out}\n")
        if quantized_blob is not None:
            if os.path.exists(args.quantized_out):
                shutil.copy2(args.quantized_out, args.quantized_out + ".bak")
                sys.stderr.write(
                    f"backed up existing quantized model -> {args.quantized_out}.bak\n"
                )
            with open(args.quantized_out, "wb") as fh:
                fh.write(quantized_blob)
            sys.stderr.write(f"wrote {args.quantized_out}\n")
        if os.path.exists(args.pattern_calibration_out):
            shutil.copy2(
                args.pattern_calibration_out,
                args.pattern_calibration_out + ".bak",
            )
            sys.stderr.write(
                "backed up existing pattern calibration -> "
                f"{args.pattern_calibration_out}.bak\n"
            )
        with open(args.pattern_calibration_out, "wb") as fh:
            fh.write(serialize_pattern_calibration_artifact(calibration_artifact))
        sys.stderr.write(f"wrote {args.pattern_calibration_out}\n")
    else:
        # default: write next to corpus for inspection, do NOT touch the crate
        scratch = os.path.join(os.path.dirname(args.corpus) or ".", f"weights_{args.features}.bin")
        with open(scratch, "wb") as fh:
            fh.write(blob)
        sys.stderr.write(f"wrote {scratch} (pass --write to update {args.out})\n")
        if quantized_blob is not None:
            quantized_scratch = os.path.join(
                os.path.dirname(args.corpus) or "",
                f"quantized_moe_{args.features}.bin",
            )
            with open(quantized_scratch, "wb") as fh:
                fh.write(quantized_blob)
            sys.stderr.write(
                f"wrote {quantized_scratch} (pass --write to update {args.quantized_out})\n"
            )
        calibration_scratch = os.path.join(
            os.path.dirname(args.corpus) or "",
            f"pattern_calibration_{args.features}.json",
        )
        with open(calibration_scratch, "wb") as fh:
            fh.write(serialize_pattern_calibration_artifact(calibration_artifact))
        sys.stderr.write(
            f"wrote {calibration_scratch} "
            f"(pass --write to update {args.pattern_calibration_out})\n"
        )
    write_model_card(
        blob,
        quantized_blob,
        feature_schema_digest,
        args,
        metrics,
        real_metrics,
        calibration_artifact,
    )


def _class_floor(metric: dict) -> float | None:
    value = metric.get("recall_at_0_40_floor")
    if isinstance(value, (float, int)):
        return float(value)
    return None


def _load_baseline_group(path: str, group: str) -> dict:
    try:
        with open(path, encoding="utf-8") as fh:
            card = json.load(fh)
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(card, dict):
        return {}
    metrics = (
        card.get("metrics", {})
        .get("real_heldout", {})
        .get(group, {})
    )
    return metrics if isinstance(metrics, dict) else {}


def _load_baseline_per_class(path: str) -> dict:
    return _load_baseline_group(path, "per_recall_sensitive_class")


def _load_baseline_per_detector(path: str) -> dict:
    return _load_baseline_group(path, "per_detector")


def _repo_path(path: str) -> pathlib.Path:
    candidate = pathlib.Path(path)
    return candidate if candidate.is_absolute() else REPO_ROOT / candidate


def _bench_report_module():
    bench_dir = str(REPO_ROOT / "benchmarks")
    if bench_dir not in sys.path:
        sys.path.insert(0, bench_dir)
    from bench import report as bench_report

    return bench_report


def six_scanner_differential_comparison(real_metrics: dict, args) -> dict:
    """Compare every positive held-out class to the benchmark differential."""
    per_class = real_metrics.get("per_class")
    if not isinstance(per_class, dict):
        raise ValueError(
            "real held-out metrics must include per_class before the "
            "six-scanner differential can be attached"
        )

    bench_report = _bench_report_module()
    results_dir = _repo_path(args.differential_results)
    results = bench_report.load_results(results_dir)
    if not results:
        raise ValueError(
            f"no benchmark RunResult JSON files found under {results_dir}; "
            "run the differential benchmark before retraining"
        )
    differential = bench_report.class_recall_differential(
        results,
        args.differential_corpus,
        bench_report.FULL_DIFFERENTIAL_SCANNERS,
    )
    rows = differential.get("rows") or {}

    missing = []
    classes = {}
    for kind, metric in sorted(per_class.items()):
        if not isinstance(metric, dict):
            continue
        n_pos = int(metric.get("n_pos") or 0)
        if n_pos <= 0:
            continue
        row = rows.get(kind)
        if row is None:
            missing.append(kind)
            continue
        best = row["best_competitor"]
        classes[kind] = {
            "heldout_n_pos": n_pos,
            "heldout_recall_at_0_40_floor": _class_floor(metric),
            "benchmark_keyhog": row["keyhog"],
            "benchmark_best_competitor": {
                "scanner": best["scanner"],
                "recall": best["recall"],
                "precision": best["precision"],
                "f1": best["f1"],
                "tp": best["tp"],
                "fn": best["fn"],
            },
            "benchmark_recall_gap": row["recall_gap"],
            "benchmark_competitors": row["competitors"],
        }

    if missing:
        raise ValueError(
            "six-scanner differential is missing positive held-out class(es) "
            f"for `{args.differential_corpus}`: {', '.join(missing)}"
        )
    if not classes:
        raise ValueError(
            "real held-out per_class metrics contain no positive-bearing class "
            "to compare against the six-scanner differential"
        )

    return {
        "corpus": differential["corpus"],
        "results_dir": str(results_dir),
        "required_scanners": list(bench_report.FULL_DIFFERENTIAL_SCANNERS),
        "scanners": differential["scanners"],
        "scanner_count": differential["scanner_count"],
        "benchmark_category_count": differential["category_count"],
        "compared_class_count": len(classes),
        "classes": classes,
    }


def per_class_gate_error(real_metrics: dict, args) -> str:
    """Guard classes whose detector policy lets the model reduce recall."""
    per_class = real_metrics.get("per_recall_sensitive_class")
    if not isinstance(per_class, dict):
        return (
            "REFUSING to write: real held-out metrics must include "
            "per_recall_sensitive_class precision/recall so aggregate recall "
            "cannot hide failures on model-authoritative paths\n"
        )

    offenders = []
    for kind, metric in sorted(per_class.items()):
        if not isinstance(metric, dict):
            continue
        n_pos = int(metric.get("n_pos") or 0)
        if n_pos < args.min_real_class_support:
            continue
        recall = _class_floor(metric)
        if recall is None or recall < args.min_real_class_recall:
            shown = "missing" if recall is None else f"{recall:.4f}"
            offenders.append(
                f"{kind} recall@0.40={shown} < floor {args.min_real_class_recall:.4f} "
                f"(n_pos={n_pos})"
            )

    regressions = []
    baseline = _load_baseline_per_class(args.baseline_model_card) if args.write else {}
    for kind, old_metric in sorted(baseline.items()):
        if kind not in per_class or not isinstance(old_metric, dict):
            continue
        new_metric = per_class.get(kind)
        if not isinstance(new_metric, dict):
            continue
        if int(new_metric.get("n_pos") or 0) < args.min_real_class_support:
            continue
        old_recall = _class_floor(old_metric)
        new_recall = _class_floor(new_metric)
        if old_recall is None or new_recall is None:
            continue
        drop = old_recall - new_recall
        if drop > args.max_real_class_recall_drop + 1e-12:
            regressions.append(
                f"{kind} recall@0.40 dropped {old_recall:.4f}->{new_recall:.4f} "
                f"(allowed {args.max_real_class_recall_drop:.4f})"
            )

    if not offenders and not regressions:
        return ""
    lines = ["REFUSING to write: per-class real held-out recall gate failed"]
    lines.extend(f"  - {item}" for item in offenders)
    lines.extend(f"  - {item}" for item in regressions)
    lines.append("")
    return "\n".join(lines)


def per_detector_gate_error(real_metrics: dict, args) -> str:
    """Return a refusal message when detector-level real recall is unsafe.

    Class gates cannot expose one broken detector hidden inside a broad class,
    so detector metrics are independently load-bearing.
    """
    per_detector = real_metrics.get("per_detector")
    if not isinstance(per_detector, dict):
        return (
            "REFUSING to write: real held-out metrics must include per_detector "
            "precision/recall so aggregate and class recall cannot hide detector failures\n"
        )

    offenders = []
    recall_sensitive = detector_policy.recall_sensitive_finding_ids()
    for detector_id in sorted(recall_sensitive):
        metric = per_detector.get(detector_id)
        if not isinstance(metric, dict):
            offenders.append(f"{detector_id} has no real held-out candidates")
            continue
        n_pos = int(metric.get("n_pos") or 0)
        if n_pos < args.min_real_detector_support:
            offenders.append(
                f"{detector_id} has {n_pos} positive held-out candidate(s), requires "
                f"{args.min_real_detector_support}"
            )
            continue
        n_neg = int(metric.get("n_neg") or 0)
        if n_neg < args.min_real_detector_negative_support:
            offenders.append(
                f"{detector_id} has {n_neg} negative held-out candidate(s), requires "
                f"{args.min_real_detector_negative_support}"
            )
            continue
        recall = _class_floor(metric)
        if recall is None or recall < args.min_real_detector_recall:
            shown = "missing" if recall is None else f"{recall:.4f}"
            offenders.append(
                f"{detector_id} recall@0.40={shown} < floor "
                f"{args.min_real_detector_recall:.4f} (n_pos={n_pos})"
            )

    regressions = []
    baseline = _load_baseline_per_detector(args.baseline_model_card) if args.write else {}
    for detector_id, old_metric in sorted(baseline.items()):
        if not detector_policy.model_can_reduce_recall(detector_id):
            continue
        new_metric = per_detector.get(detector_id)
        if not isinstance(old_metric, dict) or not isinstance(new_metric, dict):
            continue
        if int(new_metric.get("n_pos") or 0) < args.min_real_detector_support:
            continue
        old_recall = _class_floor(old_metric)
        new_recall = _class_floor(new_metric)
        if old_recall is None or new_recall is None:
            continue
        drop = old_recall - new_recall
        if drop > args.max_real_detector_recall_drop + 1e-12:
            regressions.append(
                f"{detector_id} recall@0.40 dropped {old_recall:.4f}->{new_recall:.4f} "
                f"(allowed {args.max_real_detector_recall_drop:.4f})"
            )

    if not offenders and not regressions:
        return ""
    lines = ["REFUSING to write: per-detector real held-out recall gate failed"]
    lines.extend(f"  - {item}" for item in offenders)
    lines.extend(f"  - {item}" for item in regressions)
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
