#!/usr/bin/env python3
"""Train the keyhog mixture-of-experts secret scorer and serialize weights.bin.

This is the rebuilt training pipeline referenced by
`crates/scanner/src/ml_weights.rs` ("Generated by: python3 ml/train_classifier.py").
The model architecture and the serialized layout match `ml_scorer.rs` exactly:

  gate:   Linear(D, 6) -> softmax over 6 experts
  expert: Linear(D, 32) -> ReLU -> Linear(32, 16) -> ReLU -> Linear(16, 1)
  output: fast_sigmoid( sum_e softmax(gate)[e] * expert_logit_e )

`fast_sigmoid` is the exact serve-time nonlinearity (0.5 + 0.5*x/(1+|x|)); we
train through it so the trained probabilities are the ones the Rust scanner
produces (modulo the |x|>6 hard-clamp, which only affects already-saturated
logits and never flips a threshold decision).

Serialized order (little-endian f32), matching ml_weights.rs offsets:
  gate.weight[6,D], gate.bias[6],
  then per expert e in 0..6:
    fc1.weight[32,D], fc1.bias[32], fc2.weight[16,32], fc2.bias[16],
    fc3.weight[1,16], fc3.bias[1]

Usage:
  python3 ml/corpus.py --out ml/data/corpus.jsonl
  python3 ml/train_classifier.py --corpus ml/data/corpus.jsonl \
      --out crates/scanner/src/weights.bin --features 42 --compare
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys

import numpy as np

import config_lists
import features as featmod

EXPERT_COUNT = 6
FC1 = 32
FC2 = 16


def fast_sigmoid(x):
    import torch

    return 0.5 + 0.5 * x / (1.0 + x.abs())


def load_corpus(path: str, num_features: int):
    kp, sk, tk, pk = config_lists.DEFAULT_LISTS
    with_decode = num_features == featmod.NUM_FEATURES
    X, y, kinds = [], [], []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            vec = featmod.compute_features(
                rec["text"], rec["context"], kp, sk, tk, pk, with_decode=with_decode
            )
            X.append(vec)
            y.append(float(rec["label"]))
            kinds.append(rec.get("kind", ""))
    return np.asarray(X, dtype=np.float32), np.asarray(y, dtype=np.float32), kinds


def build_model(num_features: int):
    import torch.nn as nn

    class Expert(nn.Module):
        def __init__(self, d):
            super().__init__()
            self.fc1 = nn.Linear(d, FC1)
            self.fc2 = nn.Linear(FC1, FC2)
            self.fc3 = nn.Linear(FC2, 1)

        def forward(self, x):
            import torch.nn.functional as F

            h = F.relu(self.fc1(x))
            h = F.relu(self.fc2(h))
            return self.fc3(h)  # [N,1] logit

    class MoE(nn.Module):
        def __init__(self, d):
            super().__init__()
            self.gate = nn.Linear(d, EXPERT_COUNT)
            self.experts = nn.ModuleList([Expert(d) for _ in range(EXPERT_COUNT)])

        def forward(self, x):
            import torch
            import torch.nn.functional as F

            gate_probs = F.softmax(self.gate(x), dim=1)  # [N,6]
            expert_logits = torch.cat([e(x) for e in self.experts], dim=1)  # [N,6]
            score_logit = (gate_probs * expert_logits).sum(dim=1)  # [N]
            return fast_sigmoid(score_logit)

    return MoE(num_features)


def train(X, y, num_features, epochs, seed, kinds):
    import torch

    torch.manual_seed(seed)
    rng = np.random.default_rng(seed)

    n = len(y)
    idx = rng.permutation(n)
    split = int(n * 0.85)
    tr, va = idx[:split], idx[split:]

    Xt = torch.from_numpy(X[tr])
    yt = torch.from_numpy(y[tr])
    Xv = torch.from_numpy(X[va])
    yv = torch.from_numpy(y[va])

    model = build_model(num_features)
    opt = torch.optim.Adam(model.parameters(), lr=2e-3, weight_decay=1e-5)
    bce = torch.nn.BCELoss()

    # class balance weight (corpus is ~balanced but be robust)
    pos_w = float((y[tr] == 0).sum()) / max(1.0, float((y[tr] == 1).sum()))

    best_f1, best_state = -1.0, None
    batch = 512
    for epoch in range(epochs):
        model.train()
        perm = torch.randperm(len(tr))
        for b in range(0, len(tr), batch):
            sel = perm[b : b + batch]
            xb, yb = Xt[sel], yt[sel]
            p = model(xb).clamp(1e-6, 1 - 1e-6)
            w = torch.where(yb > 0.5, torch.tensor(pos_w), torch.tensor(1.0))
            loss = (
                torch.nn.functional.binary_cross_entropy(p, yb, weight=w)
            )
            opt.zero_grad()
            loss.backward()
            opt.step()

        model.eval()
        with torch.no_grad():
            pv = model(Xv).numpy()
        f1, p_, r_ = prf(pv, y[va], 0.5)
        if f1 > best_f1:
            best_f1 = f1
            best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}

    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        pv = model(Xv).numpy()
    metrics = report(pv, y[va], [kinds[i] for i in va])
    return model, metrics


def prf(probs, labels, thr):
    pred = (probs >= thr).astype(np.float32)
    tp = float(((pred == 1) & (labels == 1)).sum())
    fp = float(((pred == 1) & (labels == 0)).sum())
    fn = float(((pred == 0) & (labels == 1)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
    return f1, prec, rec


def report(probs, labels, kinds):
    f1, prec, rec = prf(probs, labels, 0.5)
    # base64-binary FP behaviour: mean score on those negatives (want it LOW)
    bin_scores = [probs[i] for i, k in enumerate(kinds) if k == "base64-binary"]
    bin_mean = float(np.mean(bin_scores)) if bin_scores else float("nan")
    bin_flagged = (
        float(np.mean([1.0 if s >= 0.5 else 0.0 for s in bin_scores]))
        if bin_scores
        else float("nan")
    )
    return {
        "f1": f1,
        "precision": prec,
        "recall": rec,
        "n_val": int(len(labels)),
        "base64_binary_mean_score": bin_mean,
        "base64_binary_flag_rate": bin_flagged,
        "n_base64_binary_val": len(bin_scores),
    }


def probe(model, num_features: int):
    """Score canonical probe strings through the trained model so regressions
    on known cases (the Rust ml_scorer unit tests) surface here, before the
    slow Rust rebuild. Mirrors the assertions in tests/unit/ml_scorer.rs."""
    import base64
    import torch

    kp, sk, tk, pk = config_lists.DEFAULT_LISTS
    with_decode = num_features == featmod.NUM_FEATURES
    png = base64.b64encode(b"\x89PNG\r\n\x1a\n" + bytes(range(24))).decode()
    # Fragment-assembled so this source file carries no full token literal.
    ghp = "gh" + "p_" + "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij"
    cases = [
        ("real ghp PAT", ghp, f"GITHUB_TOKEN={ghp}", "high"),
        ("md5 hash", "d41d8cd98f00b204e9800998ecf8427e",
         "checksum = d41d8cd98f00b204e9800998ecf8427e", "low"),
        ("sha256 digest", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
         "sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "low"),
        ("real hex key", "9f8c2a1b4d6e7f80112233445566778899aabbccddeeff00",
         "encryption_key = 9f8c2a1b4d6e7f80112233445566778899aabbccddeeff00", "high"),
        ("placeholder", "YOUR_API_KEY_HERE", "api_key = YOUR_API_KEY_HERE", "low"),
        ("base64 PNG", png, f"avatar = {png}", "low"),
        # precision probes: bare/prose high-entropy tokens with NO anchor MUST
        # read low (these were the mirror false positives).
        ("bare token", "Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2",
         "value = Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2", "low"),
        ("prose token", "aZ4kP9qR2sT7vW1xY6bC3dE8fG0hJ5mN",
         "Session opened with handle aZ4kP9qR2sT7vW1xY6bC3dE8fG0hJ5mN. See docs.", "low"),
        # recall probe: same shape WITH a secret keyword MUST read high.
        ("anchored secret", "Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2",
         "api_key = Xk9Lm2Pq7Rs4Tv8Wy1Zb3Cd6Ef0Gh5Ij2", "high"),
    ]
    model.eval()
    out = {}
    with torch.no_grad():
        for name, text, ctx, want in cases:
            vec = featmod.compute_features(text, ctx, kp, sk, tk, pk, with_decode=with_decode)
            s = float(model(torch.tensor([vec], dtype=torch.float32))[0])
            out[name] = {"score": round(s, 3), "want": want}
    return out


def serialize(model, num_features: int) -> bytes:
    """Flatten the model into the exact little-endian f32 layout ml_weights.rs
    parses. Linear.weight is [out, in] row-major, which is precisely the
    `weights[out_idx*in + in_idx]` indexing the Rust forward pass uses."""
    sd = model.state_dict()
    buf = []

    def add(t):
        buf.append(np.asarray(t.detach().cpu().numpy(), dtype="<f4").ravel())

    add(sd["gate.weight"])  # [6, D]
    add(sd["gate.bias"])  # [6]
    for e in range(EXPERT_COUNT):
        add(sd[f"experts.{e}.fc1.weight"])  # [32, D]
        add(sd[f"experts.{e}.fc1.bias"])  # [32]
        add(sd[f"experts.{e}.fc2.weight"])  # [16, 32]
        add(sd[f"experts.{e}.fc2.bias"])  # [16]
        add(sd[f"experts.{e}.fc3.weight"])  # [1, 16]
        add(sd[f"experts.{e}.fc3.bias"])  # [1]

    flat = np.concatenate(buf)
    expected = (
        num_features * EXPERT_COUNT
        + EXPERT_COUNT
        + EXPERT_COUNT
        * (num_features * FC1 + FC1 + FC1 * FC2 + FC2 + FC2 + 1)
    )
    assert flat.size == expected, f"layout size {flat.size} != expected {expected}"
    return flat.tobytes()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default="ml/data/corpus.jsonl")
    ap.add_argument("--out", default="crates/scanner/src/weights.bin")
    ap.add_argument("--features", type=int, default=42, choices=[41, 42])
    ap.add_argument("--epochs", type=int, default=60)
    ap.add_argument("--seed", type=int, default=20260529)
    ap.add_argument("--compare", action="store_true", help="also train 41-feat baseline")
    ap.add_argument("--min-f1", type=float, default=0.85, help="refuse to write below this")
    ap.add_argument("--write", action="store_true", help="actually overwrite weights.bin")
    args = ap.parse_args()

    if args.compare:
        for d in (41, 42):
            X, y, kinds = load_corpus(args.corpus, d)
            _, m = train(X, y, d, args.epochs, args.seed, kinds)
            sys.stderr.write(f"[{d} features] {json.dumps(m)}\n")

    X, y, kinds = load_corpus(args.corpus, args.features)
    model, metrics = train(X, y, args.features, args.epochs, args.seed, kinds)
    sys.stderr.write(f"[FINAL {args.features} features] {json.dumps(metrics)}\n")
    sys.stderr.write(f"[PROBE] {json.dumps(probe(model, args.features))}\n")

    blob = serialize(model, args.features)
    sys.stderr.write(f"serialized {len(blob)} bytes ({len(blob)//4} f32)\n")

    if metrics["f1"] < args.min_f1:
        sys.stderr.write(
            f"REFUSING to write: val F1 {metrics['f1']:.4f} < floor {args.min_f1}\n"
        )
        return 1

    if args.write:
        if os.path.exists(args.out):
            shutil.copy2(args.out, args.out + ".bak")
            sys.stderr.write(f"backed up existing weights -> {args.out}.bak\n")
        with open(args.out, "wb") as fh:
            fh.write(blob)
        sys.stderr.write(f"wrote {args.out}\n")
    else:
        # default: write next to corpus for inspection, do NOT touch the crate
        scratch = os.path.join(os.path.dirname(args.corpus) or ".", f"weights_{args.features}.bin")
        with open(scratch, "wb") as fh:
            fh.write(blob)
        sys.stderr.write(f"wrote {scratch} (pass --write to update {args.out})\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
