# Funding configuration for GitHub's sponsor button.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [santhreal]
custom:
  - "https://santh.dev"
