# Docs: https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps
# Format: PEM-encoded RSA private key beginning with -----BEGIN RSA PRIVATE KEY-----
# Verify: Generate JWT and call GitHub API /app endpoint
# Prefix: -----BEGIN RSA PRIVATE KEY-----

[detector]
id = "github-app-private-key"
name = "GitHub App Private Key"
service = "github"
severity = "critical"
keywords = ["-----BEGIN RSA PRIVATE KEY-----", "-----BEGIN OPENSSH PRIVATE KEY-----", "GitHub App"]
# Private-key block: the match span is an enclosing PEM/OpenSSH key body, so
# resolution suppresses lower-specificity findings nested inside it (per-detector,
# DetectorSpec::private_key_block; was rules/detector-classification.toml list).
private_key_block = true

# The inter-marker body is restricted to the PEM base64 alphabet plus
# whitespace (`[A-Za-z0-9+/=\s]`) rather than `[\s\S]`. A real GitHub App key
# is unencrypted PKCS#1, so its body is pure base64. Excluding `-` is what makes
# the `{200,}` minimum SOUND: with `[\s\S]` the body could consume a too-short
# block's `-----END … -----BEGIN` dashes and span TWO adjacent keys to satisfy
# the 200-char floor, producing one merged finding across two distinct keys. A
# base64-only body cannot contain those dashes, so the match always terminates
# at the FIRST `-----END`, never crossing a block boundary.
[[detector.patterns]]
regex = "-----BEGIN (RSA|OPENSSH) PRIVATE KEY-----[A-Za-z0-9+/=\\s]{200,}?-----END (RSA|OPENSSH) PRIVATE KEY-----"
description = "PEM-encoded private key for GitHub App authentication"

[[detector.patterns]]
regex = "(?:github[_-]?app|GITHUB[_-]?APP)[=:\\s\"'']+(-----BEGIN (?:RSA|OPENSSH) PRIVATE KEY-----[A-Za-z0-9+/=\\s]{200,}?-----END (?:RSA|OPENSSH) PRIVATE KEY-----)"
description = "GitHub App private key with context anchor"
group = 1

[[detector.tests]]
test_positive = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEA7n2K9xR4vQ1mWcZ8hLbF3jD5sT6yU0pN2aG4eH7iO9kB1lM3rV5wX8zC0dQ2fS4gJ6kP8mR0tU2wY4aB6cD8eF0gH2iJ4kL6mN8oP0qR2sT4uV6wX8yZ0aB2cD4eF6gH8iJ0kL2mN4oP6qR8sT0uV2wX4yZ6aB8cD0eF2gH4iJ6kL8mN0oP2qR4sT6uV8wX0yZ2aB4cD6eF8gH0iJ2kL4\n-----END RSA PRIVATE KEY-----"
test_negative = "-----BEGIN RSA PRIVATE KEY-----=short"
