//! WHY: Lockfile exclusion parity and precision contract (Row 17, Row 88):
//! Every major ecosystem lockfile registered in `rules/default_excludes.toml` must
//! be excluded by default during scans so that hash-rich lockfile trees do not flood
//! output with false positives, while remaining fully scannable when default excludes
//! are explicitly disabled. This test derives the lockfile variant space dynamically
//! from `rules/default_excludes.toml` at runtime and verifies detection precision over
//! realistic hash-rich fixture bytes with planted secrets in both directions.
//!
//! WHAT IT DOES NOT CATCH:
//! Custom proprietary in-house lockfile formats that are not registered in the Tier-B
//! `rules/default_excludes.toml` configuration table.

use keyhog_core::Source;
use keyhog_sources::FilesystemSource;
use std::collections::BTreeSet;
use std::path::Path;
use toml::Value;

fn repo_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates/")
        .parent()
        .expect("repo root")
}

fn load_default_exclude_filenames() -> BTreeSet<String> {
    let root = repo_root();
    let excludes_path = root.join("rules/default_excludes.toml");
    assert!(
        excludes_path.exists(),
        "rules/default_excludes.toml must exist"
    );

    let content =
        std::fs::read_to_string(&excludes_path).expect("read rules/default_excludes.toml");
    let parsed: Value = toml::from_str(&content).expect("parse rules/default_excludes.toml");

    let filenames_array = parsed
        .get("default_excludes")
        .and_then(|t| t.get("filenames"))
        .and_then(|v| v.as_array())
        .expect("default_excludes.filenames array must exist");

    filenames_array
        .iter()
        .filter_map(|v| v.as_str().map(|s| s.to_string()))
        .collect()
}

fn generate_hash_rich_lockfile_content(filename: &str, planted_secret: &str) -> String {
    match filename {
        "package-lock.json" => format!(
            r#"{{
  "name": "example-app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {{
    "": {{
      "name": "example-app",
      "version": "1.0.0",
      "dependencies": {{
        "lodash": "^4.17.21"
      }}
    }},
    "node_modules/lodash": {{
      "version": "4.17.21",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
      "integrity": "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==",
      "dev": false,
      "_comment": "{planted_secret}"
    }}
  }}
}}
"#
        ),
        "yarn.lock" => format!(
            r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT MANUALLY.
# yarn lockfile v1

"lodash@^4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c5c30fe56463a0a0e450498670bc300d0e"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==
  # planted credential: {planted_secret}
"#
        ),
        "pnpm-lock.yaml" => format!(
            r#"lockfileVersion: '9.0'
settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false
importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21
packages:
  lodash@4.17.21:
    resolution: {{integrity: sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==}}
    # planted: {planted_secret}
"#
        ),
        "cargo.lock" => format!(
            r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "example-crate"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "c8e35924721c1559ac58e7277b87a7d86320dd5d1fb546857dce477044492170"
# metadata secret: {planted_secret}
"#
        ),
        "go.sum" => format!(
            r#"github.com/golang/protobuf v1.5.0/go.mod h1:6lQm7++v288ijVreL4dnSdBZXoCra8c4JddLSub2xyw=
github.com/golang/protobuf v1.5.2 h1:ROPKBNFfQgOUMifHyP+KYbvpjbdoFNs+aK7Yl4PfbO4=
github.com/golang/protobuf v1.5.2/go.mod h1:czJhggtegir0DGbEReap3310id78YwcGY2XFi_DCmGo=
# secret: {planted_secret}
golang.org/x/sync v0.0.0-20210220032951-036812b2e83c h1:5KSlGYw3uFtHBGg06PDqmQ+Chkg5PE2bRK36CumlQ1c=
"#
        ),
        "gemfile.lock" => format!(
            r#"GEM
  remote: https://rubygems.org/
  specs:
    rack (2.2.4)
    rake (13.0.6)

PLATFORMS
  ruby

DEPENDENCIES
  rack (~> 2.2)
  rake (~> 13.0)

RUBY VERSION
   ruby 3.1.2p20

CHECKSUMS
  rack (2.2.4) = "5f23d6a9e159074b1e56b46b1d1645e523f339cfdaee6a4b" # {planted_secret}
"#
        ),
        "poetry.lock" => format!(
            r#"# This file is automatically generated by Poetry.
[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = [
    {{file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:58cd2187c01e70e6e2f7e2b2f7a77a0fb4f285075a270924e18d5e6146b12864"}},
]
# auth: {planted_secret}
"#
        ),
        "pipfile.lock" => format!(
            r#"{{
    "_meta": {{
        "hash": {{
            "sha256": "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
        }},
        "pipfile-spec": 6,
        "requires": {{
            "python_version": "3.11"
        }}
    }},
    "default": {{
        "requests": {{
            "hashes": [
                "sha256:58cd2187c01e70e6e2f7e2b2f7a77a0fb4f285075a270924e18d5e6146b12864"
            ],
            "index": "pypi",
            "version": "==2.31.0",
            "secret": "{planted_secret}"
        }}
    }}
}}
"#
        ),
        "uv.lock" => format!(
            r#"version = 1
revision = 1
requires-python = ">=3.11"

[[package]]
name = "fastapi"
version = "0.111.0"
source = {{ registry = "https://pypi.org/simple" }}
sdist = {{ hash = "sha256:b1d830b57e79b9b4f2c00222f7b172a11b6c7dbcd4b07e5c69786a3449339e14" }}
# {planted_secret}
"#
        ),
        "pdm.lock" => format!(
            r#"# This file is @generated by PDM.
lock_version = "2.0"

[[package]]
name = "urllib3"
version = "2.2.1"
files = [
    {{file = "urllib3-2.2.1-py3-none-any.whl", hash = "sha256:a7f2937965461dc32f30453303666dd95c2f9050d2bc437e408d6d6349c71b69"}},
]
# token: {planted_secret}
"#
        ),
        "composer.lock" => format!(
            r#"{{
    "_readme": [
        "This file locks the dependencies of your project to a known state"
    ],
    "content-hash": "1234567890abcdef1234567890abcdef",
    "packages": [
        {{
            "name": "guzzlehttp/guzzle",
            "version": "7.8.1",
            "dist": {{
                "type": "zip",
                "url": "https://api.github.com/repos/guzzle/guzzle/zipball/4d04274e24c1ff74e7e69647484f7440d0474034",
                "reference": "4d04274e24c1ff74e7e69647484f7440d0474034",
                "shasum": "abcdef1234567890abcdef1234567890abcdef12"
            }},
            "secret": "{planted_secret}"
        }}
    ]
}}
"#
        ),
        "flake.lock" => format!(
            r#"{{
  "nodes": {{
    "nixpkgs": {{
      "locked": {{
        "lastModified": 1715699908,
        "narHash": "sha256-R3N/lFkMhXG8z3x9tH5f+J9D4kH1A5L4L4P9qH7mN1g=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "8071e626e84d720b0800fa1b7f0df8877bc954f6",
        "type": "github"
      }},
      "original": {{
        "owner": "NixOS",
        "ref": "nixpkgs-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }}
    }},
    "root": {{
      "inputs": {{
        "nixpkgs": "nixpkgs"
      }},
      "meta": {{
        "token": "{planted_secret}"
      }}
    }}
  }},
  "root": "root",
  "version": 7
}}
"#
        ),
        "mix.lock" => format!(
            r#"%{{
  "plug": {{:hex, :plug, "1.14.0", "56b19a164da3e9e1bbba806db73dc2d1d05fdc94e43e74bebb3d7be21a364177", [:mix], [], "hexpm", "58f448c90be68d18471e44efb48074d2b27072fdf8186111fdb166b26d8338da"}},
  # key: {planted_secret}
}}
"#
        ),
        "pubspec.lock" => format!(
            r#"# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  path:
    dependency: "direct main"
    description:
      name: path
      sha256: "087ce40c7937025d57fa918383bd93a9b319724126973b60df2212f47e3a32f4"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.0"
# secret: {planted_secret}
"#
        ),
        "podfile.lock" => format!(
            r#"PODS:
  - Alamofire (5.9.1)

DEPENDENCIES:
  - Alamofire (~> 5.9.1)

SPEC CHECKSUMS:
  Alamofire: 593740e53a234720973a9856f64249a888c031d2

PODFILE CHECKSUM: 9387405820489582049582049582049582049582 # {planted_secret}
COCOAPODS: 1.15.2
"#
        ),
        "conan.lock" => format!(
            r#"{{
 "version": "0.4",
 "graph_lock": {{
  "nodes": {{
   "0": {{
    "ref": "zlib/1.2.11#abcdef1234567890abcdef1234567890",
    "rrev": "abcdef1234567890abcdef1234567890",
    "package_id": "d50a0d523d98c15bb147b18799d475e823576fc1",
    "secret": "{planted_secret}"
   }}
  }}
 }}
}}
"#
        ),
        "cache.json" => format!(
            r#"{{
  "cacheVersion": 2,
  "manifestHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "entries": {{
    "app.js": {{ "hash": "d41d8cd98f00b204e9800998ecf8427e", "token": "{planted_secret}" }}
  }}
}}
"#
        ),
        "angular.json" => format!(
            r#"{{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {{
    "my-app": {{
      "projectType": "application",
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {{
        "build": {{
          "options": {{
            "outputPath": "dist/my-app",
            "token": "{planted_secret}"
          }}
        }}
      }}
    }}
  }}
}}
"#
        ),
        _ => format!(
            r#"# Lockfile metadata for {filename}
hash = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
integrity = "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg=="
secret = "{planted_secret}"
"#
        ),
    }
}

#[test]
fn default_excludes_rule_table_is_bidirectionally_verified_over_fixture_bytes() {
    let filenames = load_default_exclude_filenames();
    assert!(
        !filenames.is_empty(),
        "default_excludes.filenames must contain entries"
    );

    for filename in &filenames {
        let temp_dir = tempfile::tempdir().expect("create temp dir for lockfile fixture");
        let root = temp_dir.path();

        let source_secret = format!(
            "ghp_plantedsource_{}_0123456789ABCDEF012345",
            filename.replace('.', "_")
        );
        let lockfile_secret = format!(
            "ghp_plantedlockfile_{}_0123456789ABCDEF012345",
            filename.replace('.', "_")
        );

        let src_dir = root.join("src");
        std::fs::create_dir_all(&src_dir).expect("create src dir");
        let source_file_path = src_dir.join("index.js");
        std::fs::write(
            &source_file_path,
            format!("// Real source file\nconst API_KEY = \"{source_secret}\";\n"),
        )
        .expect("write source file");

        let lockfile_path = root.join(filename);
        let lockfile_content = generate_hash_rich_lockfile_content(filename, &lockfile_secret);
        std::fs::write(&lockfile_path, lockfile_content).expect("write lockfile fixture");

        // Direction 1: Default excludes ENABLED (`respect_default_excludes: true`)
        // - Lockfile must be completely excluded from emitted chunks
        // - The source file secret must be emitted with its path
        {
            let source = FilesystemSource::new(root.to_path_buf()).with_default_excludes(true);
            let chunks: Vec<keyhog_core::Chunk> = source.chunks().filter_map(Result::ok).collect();

            let has_source_secret = chunks.iter().any(|c| c.data.contains(&source_secret));
            let has_lockfile_secret = chunks.iter().any(|c| c.data.contains(&lockfile_secret));

            assert!(
                has_source_secret,
                "Default excludes enabled: source secret in 'src/index.js' must be discovered for fixture '{filename}'"
            );
            assert!(
                !has_lockfile_secret,
                "Default excludes enabled: lockfile secret in '{filename}' must be EXCLUDED and not emitted"
            );

            for chunk in &chunks {
                if let Some(path) = &chunk.metadata.path {
                    assert!(
                        !path.ends_with(filename),
                        "Default excludes enabled: chunk path '{path}' must not match excluded lockfile '{filename}'"
                    );
                }
            }
        }

        // Direction 2: Default excludes DISABLED (`respect_default_excludes: false`)
        // - Lockfile must be SCANNED and emitted in chunks
        // - Both the source file secret and the lockfile secret must be emitted with their respective paths
        {
            let source = FilesystemSource::new(root.to_path_buf()).with_default_excludes(false);
            let chunks: Vec<keyhog_core::Chunk> = source.chunks().filter_map(Result::ok).collect();

            let has_source_secret = chunks.iter().any(|c| c.data.contains(&source_secret));
            let has_lockfile_secret = chunks.iter().any(|c| c.data.contains(&lockfile_secret));

            assert!(
                has_source_secret,
                "Default excludes disabled: source secret in 'src/index.js' must be discovered for fixture '{filename}'"
            );
            assert!(
                has_lockfile_secret,
                "Default excludes disabled: lockfile secret in '{filename}' must be DISCOVERED when default excludes are disabled"
            );

            let lockfile_chunk_emitted = chunks.iter().any(|c| {
                c.metadata
                    .path
                    .as_deref()
                    .map(|p| p.ends_with(filename))
                    .unwrap_or(false)
            });
            assert!(
                lockfile_chunk_emitted,
                "Default excludes disabled: a chunk with path ending in '{filename}' must be emitted"
            );
        }
    }
}

#[test]
fn default_excludes_case_insensitivity_parity() {
    let filenames = load_default_exclude_filenames();

    // Verify case-insensitive exclusion behavior on sample variants (e.g. Cargo.lock vs cargo.lock)
    for filename in &filenames {
        let temp_dir = tempfile::tempdir().expect("create temp dir");
        let root = temp_dir.path();

        let uppercase_variant = if filename.contains('-') {
            filename
                .split('-')
                .map(|part| {
                    let mut c = part.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                    }
                })
                .collect::<Vec<_>>()
                .join("-")
        } else {
            let mut c = filename.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        };

        let lockfile_secret = format!(
            "ghp_variant_{}_0123456789ABCDEF012345",
            filename.replace('.', "_")
        );
        let lockfile_path = root.join(&uppercase_variant);
        let lockfile_content = generate_hash_rich_lockfile_content(filename, &lockfile_secret);
        std::fs::write(&lockfile_path, lockfile_content).expect("write lockfile variant");

        // Direction 1: Excluded
        {
            let source = FilesystemSource::new(root.to_path_buf()).with_default_excludes(true);
            let chunks: Vec<keyhog_core::Chunk> = source.chunks().filter_map(Result::ok).collect();
            let has_lockfile_secret = chunks.iter().any(|c| c.data.contains(&lockfile_secret));
            assert!(
                !has_lockfile_secret,
                "Case variant '{uppercase_variant}' must be excluded by default_excludes (case-insensitive)"
            );
        }

        // Direction 2: Included when default excludes disabled
        {
            let source = FilesystemSource::new(root.to_path_buf()).with_default_excludes(false);
            let chunks: Vec<keyhog_core::Chunk> = source.chunks().filter_map(Result::ok).collect();
            let has_lockfile_secret = chunks.iter().any(|c| c.data.contains(&lockfile_secret));
            assert!(
                has_lockfile_secret,
                "Case variant '{uppercase_variant}' must be included when default excludes disabled"
            );
        }
    }
}
