//! Property tier for `extract_printable_strings` (reached via the
//! `SourceTestApi` facade) — the `strings(1)`-equivalent that turns a binary
//! blob (ELF/PE/.NET, PDF, WASM, archive members) into the printable runs the
//! scanner then searches for credentials. The fixed-vector twins
//! (`tests/unit/strings_extract.rs`, `tests/regression_binary_strings_*`) pin a
//! handful of hand-built inputs; this file sweeps the extractor's invariants
//! over generated bytes so a regression in the run accumulation, the `min_len`
//! floor, or the UTF-16LE pass surfaces on a shape nobody wrote a vector for.
//!
//! Invariants proved here:
//!   * SHAPE + ROBUSTNESS — over ARBITRARY bytes, every extracted string is made
//!     only of printable bytes (`ascii_graphic | space | tab`, the extractor's
//!     own alphabet) and is at least `min_len` long, and the extractor never
//!     panics. A run that leaked a control byte, or a sub-`min_len` fragment,
//!     would be a real recall/precision bug.
//!   * MIN_LEN MONOTONICITY — raising the length floor only ever DROPS strings:
//!     the runs are the same byte scan, so `extract(bytes, hi)` is a
//!     sub-multiset of `extract(bytes, lo)` for `lo <= hi`. A floor that added
//!     or lengthened a run when raised would be incoherent.
//!   * RECALL — a printable run of length `>= min_len` delimited by NUL bytes
//!     (the canonical shape of a secret embedded in a binary) is recovered
//!     verbatim. This is the extractor's whole job; the fixed vectors only
//!     sample one or two such runs.
//!
//! Base build: the extractor facade needs no cargo feature.

use keyhog_sources::testing::{SourceTestApi, TestApi};
use proptest::prelude::*;
use std::collections::HashMap;

/// The extractor's printable alphabet, mirrored here as the contract-of-record:
/// a run is exactly a maximal span of these bytes.
fn is_printable(b: u8) -> bool {
    b.is_ascii_graphic() || b == b' ' || b == b'\t'
}

/// A non-empty printable run (chars drawn from the extractor's own alphabet),
/// so it is recovered as a single contiguous string when NUL-delimited.
fn printable_run() -> impl Strategy<Value = String> {
    let alphabet: Vec<u8> = (b'!'..=b'~').chain([b' ', b'\t']).collect();
    prop::collection::vec(prop::sample::select(alphabet), 2..=40)
        .prop_map(|bytes| String::from_utf8(bytes).expect("printable alphabet is valid UTF-8"))
}

fn value_counts(strings: &[keyhog_core::SensitiveString]) -> HashMap<String, usize> {
    let mut counts = HashMap::new();
    for s in strings {
        *counts.entry(s.as_ref().to_string()).or_insert(0) += 1;
    }
    counts
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(4_000))]

    /// Every extracted string is all-printable and at least `min_len` long, over
    /// arbitrary bytes — which also proves the extractor never panics.
    #[test]
    fn every_extracted_string_is_printable_and_meets_min_len(
        bytes in prop::collection::vec(any::<u8>(), 0..=512),
        min_len in 1usize..=20,
    ) {
        for s in TestApi.extract_printable_strings(&bytes, min_len) {
            let text = s.as_ref();
            // All chars are single-byte ASCII, so byte length == char length ==
            // the `current_string.len()` the extractor thresholds on.
            prop_assert!(
                text.len() >= min_len,
                "extracted {:?} is shorter than min_len {}",
                text, min_len
            );
            prop_assert!(
                text.bytes().all(is_printable),
                "extracted {:?} contains a non-printable byte",
                text
            );
        }
    }

    /// Raising `min_len` only drops strings: `extract(bytes, hi)` is a
    /// sub-multiset of `extract(bytes, lo)` for `lo <= hi`.
    #[test]
    fn raising_min_len_only_drops_strings(
        bytes in prop::collection::vec(any::<u8>(), 0..=512),
        a in 1usize..=12,
        b in 1usize..=12,
    ) {
        let (lo, hi) = if a <= b { (a, b) } else { (b, a) };
        let low = value_counts(&TestApi.extract_printable_strings(&bytes, lo));
        let high = value_counts(&TestApi.extract_printable_strings(&bytes, hi));
        for (value, high_count) in &high {
            let low_count = low.get(value).copied().unwrap_or(0);
            prop_assert!(
                low_count >= *high_count,
                "raising min_len {} -> {} yielded {:?} x{} not covered by the lower floor (x{})",
                lo, hi, value, high_count, low_count
            );
        }
    }

    /// A NUL-delimited printable run of length >= min_len is recovered verbatim.
    #[test]
    fn a_nul_flanked_printable_run_is_recovered(
        run in printable_run(),
        min_len in 2usize..=8,
    ) {
        prop_assume!(run.len() >= min_len);
        let mut bytes = vec![0u8];
        bytes.extend_from_slice(run.as_bytes());
        bytes.push(0u8);
        let out = TestApi.extract_printable_strings(&bytes, min_len);
        prop_assert!(
            out.iter().any(|s| s.as_ref() == run),
            "a NUL-flanked printable run of len {} (>= min_len {}) must be extracted verbatim",
            run.len(), min_len
        );
    }
}
