#![allow(clippy::needless_borrow, clippy::needless_update, clippy::useless_vec)]

mod support;

pub mod concurrent;
pub mod contract;
pub mod integration;
pub mod regression;
// Standalone `regression_*.rs` files are aggregated here so the single CI step
// `cargo test -p keyhog-scanner --test all_tests` actually runs them. A test file
// that lives in `tests/` but is NOT `#[path]`-included here (and not explicitly
// `--test`-listed in a workflow) is a CI-orphan: it never runs, its assertions
// are dead weight, and the regression it guards can ship silently. The
// `scripts/gates/recall_locks_wired.py` gate fails the build if any top-level
// `regression_*.rs` is orphaned, so this list stays exhaustive. Keep sorted.
#[path = "regression_ac_literal_prefilter.rs"]
pub mod regression_ac_literal_prefilter;
#[path = "regression_ac_overlap_shadow.rs"]
pub mod regression_ac_overlap_shadow;
#[path = "regression_active_detector_suppression_policy.rs"]
pub mod regression_active_detector_suppression_policy;
#[path = "regression_ai_provider_key_recall.rs"]
pub mod regression_ai_provider_key_recall;
#[path = "regression_ai_vendor_prefix_token_recall.rs"]
pub mod regression_ai_vendor_prefix_token_recall;
#[path = "regression_alphabet_filter_prefilter.rs"]
pub mod regression_alphabet_filter_prefilter;
#[path = "regression_autoroute_decision.rs"]
pub mod regression_autoroute_decision;
#[path = "regression_aws_detector_internals.rs"]
pub mod regression_aws_detector_internals;
#[path = "regression_backend_trigger_parity.rs"]
pub mod regression_backend_trigger_parity;
#[path = "regression_bare_authorization_no_fp.rs"]
pub mod regression_bare_authorization_no_fp;
#[path = "regression_bare_service_url_recall.rs"]
pub mod regression_bare_service_url_recall;
#[path = "regression_base32_decode.rs"]
pub mod regression_base32_decode;
#[path = "regression_base32_decoder.rs"]
pub mod regression_base32_decoder;
#[path = "regression_base64_variant_boundary.rs"]
pub mod regression_base64_variant_boundary;
#[path = "regression_bigram_bloom.rs"]
pub mod regression_bigram_bloom;
#[path = "regression_bigram_bloom_filter.rs"]
pub mod regression_bigram_bloom_filter;
#[path = "regression_bigram_bloom_no_false_negative_proptest.rs"]
pub mod regression_bigram_bloom_no_false_negative_proptest;
#[path = "regression_billing_vendor_token_recall.rs"]
pub mod regression_billing_vendor_token_recall;
#[path = "regression_caesar_decoder.rs"]
pub mod regression_caesar_decoder;
#[path = "regression_caesar_shift_all.rs"]
pub mod regression_caesar_shift_all;
#[path = "regression_charclass_prefix_expansion_recall.rs"]
pub mod regression_charclass_prefix_expansion_recall;
#[path = "regression_checksum_boundary_no_downgrade.rs"]
pub mod regression_checksum_boundary_no_downgrade;
#[path = "regression_checksum_registry_crc.rs"]
pub mod regression_checksum_registry_crc;
#[path = "regression_cloud_credential_recall.rs"]
pub mod regression_cloud_credential_recall;
#[path = "regression_cloud_infra_db_token_recall.rs"]
pub mod regression_cloud_infra_db_token_recall;
#[path = "regression_coalesced_large_chunk_entropy_parity.rs"]
pub mod regression_coalesced_large_chunk_entropy_parity;
#[path = "regression_coalesced_reassembly_parity.rs"]
pub mod regression_coalesced_reassembly_parity;
#[path = "regression_compile_companion_capture_group.rs"]
pub mod regression_compile_companion_capture_group;
#[path = "regression_confidence_nan_sanitize.rs"]
pub mod regression_confidence_nan_sanitize;
#[path = "regression_context_syntax_recall.rs"]
pub mod regression_context_syntax_recall;
#[path = "regression_context_window.rs"]
pub mod regression_context_window;
#[path = "regression_cpu_decoder_parity.rs"]
pub mod regression_cpu_decoder_parity;
#[path = "regression_creddata_bearer_authorization_recall.rs"]
pub mod regression_creddata_bearer_authorization_recall;
#[path = "regression_creddata_hex_key_recall.rs"]
pub mod regression_creddata_hex_key_recall;
#[path = "regression_creddata_key_anchor_precision_contract.rs"]
pub mod regression_creddata_key_anchor_precision_contract;
#[path = "regression_creddata_keyword_suffix_recall.rs"]
pub mod regression_creddata_keyword_suffix_recall;
#[path = "regression_creddata_random_password_recall.rs"]
pub mod regression_creddata_random_password_recall;
#[path = "regression_creddata_sql_cli_password_recall.rs"]
pub mod regression_creddata_sql_cli_password_recall;
#[path = "regression_creddata_url_credentials_recall.rs"]
pub mod regression_creddata_url_credentials_recall;
#[path = "regression_creddata_vendor_prefixed_key_recall.rs"]
pub mod regression_creddata_vendor_prefixed_key_recall;
#[path = "regression_credential_uri_scheme_coverage.rs"]
pub mod regression_credential_uri_scheme_coverage;
#[path = "regression_crlf_entropy_line_offsets.rs"]
pub mod regression_crlf_entropy_line_offsets;
#[path = "regression_db_connection_string_recall.rs"]
pub mod regression_db_connection_string_recall;
#[path = "regression_decode_cap_bounds.rs"]
pub mod regression_decode_cap_bounds;
#[path = "regression_decode_density_boundary.rs"]
pub mod regression_decode_density_boundary;
#[path = "regression_decode_density_gate.rs"]
pub mod regression_decode_density_gate;
#[path = "regression_decode_json_escapes.rs"]
pub mod regression_decode_json_escapes;
#[path = "regression_decode_primitive_bounds.rs"]
pub mod regression_decode_primitive_bounds;
#[path = "regression_decode_registry_names.rs"]
pub mod regression_decode_registry_names;
#[path = "regression_decode_through_recall.rs"]
pub mod regression_decode_through_recall;
#[path = "regression_decode_through_strict.rs"]
pub mod regression_decode_through_strict;
#[path = "regression_decode_url_plus.rs"]
pub mod regression_decode_url_plus;
#[path = "regression_decoded_generic_entropy_guard.rs"]
pub mod regression_decoded_generic_entropy_guard;
#[path = "regression_deep_preset_recovery.rs"]
pub mod regression_deep_preset_recovery;
#[path = "regression_deepl_bare_key_recall.rs"]
pub mod regression_deepl_bare_key_recall;
#[path = "regression_detector_identity_propagation.rs"]
pub mod regression_detector_identity_propagation;
#[path = "regression_detector_keyword_index.rs"]
pub mod regression_detector_keyword_index;
#[path = "regression_detector_min_len_runtime.rs"]
pub mod regression_detector_min_len_runtime;
#[path = "regression_detector_registry_integrity.rs"]
pub mod regression_detector_registry_integrity;
#[path = "regression_devplatform_monitoring_token_recall.rs"]
pub mod regression_devplatform_monitoring_token_recall;
#[path = "regression_devtool_vendor_token_recall.rs"]
pub mod regression_devtool_vendor_token_recall;
#[path = "regression_distinctive_infix_anchor_recall.rs"]
pub mod regression_distinctive_infix_anchor_recall;
#[path = "regression_dogfood_policy_prose_precision.rs"]
pub mod regression_dogfood_policy_prose_precision;
#[path = "regression_dot_concatenation.rs"]
pub mod regression_dot_concatenation;
#[path = "regression_dotfile_credentials.rs"]
pub mod regression_dotfile_credentials;
#[path = "regression_dotted_authentication_key_recall.rs"]
pub mod regression_dotted_authentication_key_recall;
#[path = "regression_edge_platform_token_recall.rs"]
pub mod regression_edge_platform_token_recall;
#[path = "regression_email_vendor_token_recall.rs"]
pub mod regression_email_vendor_token_recall;
#[path = "regression_encoded_benign_text_suppression.rs"]
pub mod regression_encoded_benign_text_suppression;
#[path = "regression_entropy_base64_protobuf_decoys.rs"]
pub mod regression_entropy_base64_protobuf_decoys;
#[path = "regression_entropy_confidence_truth.rs"]
pub mod regression_entropy_confidence_truth;
#[path = "regression_entropy_floor_config.rs"]
pub mod regression_entropy_floor_config;
#[path = "regression_entropy_histogram.rs"]
pub mod regression_entropy_histogram;
#[path = "regression_entropy_keyword_list.rs"]
pub mod regression_entropy_keyword_list;
#[path = "regression_entropy_sentence_handle.rs"]
pub mod regression_entropy_sentence_handle;
#[path = "regression_entropy_unique_char_count.rs"]
pub mod regression_entropy_unique_char_count;
#[path = "regression_env_file_source.rs"]
pub mod regression_env_file_source;
#[path = "regression_finalize_confidence_proptest.rs"]
pub mod regression_finalize_confidence_proptest;
#[path = "regression_finalize_report_confidence_pipeline.rs"]
pub mod regression_finalize_report_confidence_pipeline;
#[path = "regression_generic_bridge_padded_log_field.rs"]
pub mod regression_generic_bridge_padded_log_field;
#[path = "regression_generic_detector_entropy_override.rs"]
pub mod regression_generic_detector_entropy_override;
#[path = "regression_github_app_pem_boundary.rs"]
pub mod regression_github_app_pem_boundary;
#[path = "regression_github_pat_boundary.rs"]
pub mod regression_github_pat_boundary;
#[path = "regression_gitlab_token_completeness_recall.rs"]
pub mod regression_gitlab_token_completeness_recall;
#[path = "regression_gpu_region_presence_batch_parity.rs"]
pub mod regression_gpu_region_presence_batch_parity;
#[path = "regression_hex_decoder_through.rs"]
pub mod regression_hex_decoder_through;
#[path = "regression_hexbody_vendor_prefix_floor.rs"]
pub mod regression_hexbody_vendor_prefix_floor;
#[path = "regression_hot_path_fp_context_parity.rs"]
pub mod regression_hot_path_fp_context_parity;
#[path = "regression_hot_pattern_process_parity.rs"]
pub mod regression_hot_pattern_process_parity;
#[path = "regression_hot_token_right_boundary.rs"]
pub mod regression_hot_token_right_boundary;
#[path = "regression_html_entity_decode.rs"]
pub mod regression_html_entity_decode;
#[path = "regression_iac_secret_recall.rs"]
pub mod regression_iac_secret_recall;
#[path = "regression_infra_vendor_token_recall.rs"]
pub mod regression_infra_vendor_token_recall;
#[path = "regression_into_matches_dedup_order_invariant.rs"]
pub mod regression_into_matches_dedup_order_invariant;
#[path = "regression_javascript_static_recovery.rs"]
pub mod regression_javascript_static_recovery;
#[path = "regression_javascript_static_recovery_rejections.rs"]
pub mod regression_javascript_static_recovery_rejections;
#[path = "regression_json_decoder_through.rs"]
pub mod regression_json_decoder_through;
#[path = "regression_jwt_header_field_order_recall.rs"]
pub mod regression_jwt_header_field_order_recall;
#[path = "regression_jwt_signing_secret_recall.rs"]
pub mod regression_jwt_signing_secret_recall;
#[path = "regression_keyword_bridge.rs"]
pub mod regression_keyword_bridge;
#[path = "regression_keyword_bridge_floor.rs"]
pub mod regression_keyword_bridge_floor;
#[path = "regression_keyword_predicate_union.rs"]
pub mod regression_keyword_predicate_union;
#[path = "regression_keyword_separator_canonicalization.rs"]
pub mod regression_keyword_separator_canonicalization;
#[path = "regression_kubeconfig_k8s_recall.rs"]
pub mod regression_kubeconfig_k8s_recall;
#[path = "regression_leading_assertion_and_alternation_prefix_recall.rs"]
pub mod regression_leading_assertion_and_alternation_prefix_recall;
#[path = "regression_match_dedup_key.rs"]
pub mod regression_match_dedup_key;
#[path = "regression_messaging_vendor_token_recall.rs"]
pub mod regression_messaging_vendor_token_recall;
#[path = "regression_mime_encoded_word_decode.rs"]
pub mod regression_mime_encoded_word_decode;
#[path = "regression_min_confidence_floor.rs"]
pub mod regression_min_confidence_floor;
#[path = "regression_ml_features_bigram_stats.rs"]
pub mod regression_ml_features_bigram_stats;
#[path = "regression_ml_production_weight_golden.rs"]
pub mod regression_ml_production_weight_golden;
#[path = "regression_ml_scorer_sigmoid.rs"]
pub mod regression_ml_scorer_sigmoid;
#[path = "regression_multiline_concat_assignment_strip.rs"]
pub mod regression_multiline_concat_assignment_strip;
#[path = "regression_multiline_concat_markers.rs"]
pub mod regression_multiline_concat_markers;
#[path = "regression_multiline_fragment.rs"]
pub mod regression_multiline_fragment;
#[path = "regression_multiline_join.rs"]
pub mod regression_multiline_join;
#[path = "regression_multiline_structural.rs"]
pub mod regression_multiline_structural;
#[path = "regression_named_canonical_hex_key_recall.rs"]
pub mod regression_named_canonical_hex_key_recall;
#[path = "regression_named_detector_anchor_floor_recall.rs"]
pub mod regression_named_detector_anchor_floor_recall;
#[path = "regression_nested_base64.rs"]
pub mod regression_nested_base64;
#[path = "regression_observability_ci_token_recall.rs"]
pub mod regression_observability_ci_token_recall;
#[path = "regression_observability_token_recall.rs"]
pub mod regression_observability_token_recall;
#[path = "regression_octal_decode_gate.rs"]
pub mod regression_octal_decode_gate;
#[path = "regression_octal_escape_short_escapes.rs"]
pub mod regression_octal_escape_short_escapes;
#[path = "regression_overbroad_detectors_precision.rs"]
pub mod regression_overbroad_detectors_precision;
#[path = "regression_package_registry_token_recall.rs"]
pub mod regression_package_registry_token_recall;
#[path = "regression_password_slot_mask_suppression.rs"]
pub mod regression_password_slot_mask_suppression;
#[path = "regression_payment_vendor_token_recall.rs"]
pub mod regression_payment_vendor_token_recall;
#[path = "regression_per_pattern_weak_anchor_recall.rs"]
pub mod regression_per_pattern_weak_anchor_recall;
#[path = "regression_prefilter_alphabet_union.rs"]
pub mod regression_prefilter_alphabet_union;
#[path = "regression_prefilter_cache.rs"]
pub mod regression_prefilter_cache;
#[path = "regression_prefilter_trigger_union.rs"]
pub mod regression_prefilter_trigger_union;
#[path = "regression_prefix_storm_backend_parity.rs"]
pub mod regression_prefix_storm_backend_parity;
#[path = "regression_private_key_block_resolution.rs"]
pub mod regression_private_key_block_resolution;
#[path = "regression_private_key_caesar_decode_suppression.rs"]
pub mod regression_private_key_caesar_decode_suppression;
#[path = "regression_private_key_decode_child_resolution.rs"]
pub mod regression_private_key_decode_child_resolution;
#[path = "regression_private_key_variant_matrix.rs"]
pub mod regression_private_key_variant_matrix;
#[path = "regression_putty_private_key.rs"]
pub mod regression_putty_private_key;
#[path = "regression_quoted_printable.rs"]
pub mod regression_quoted_printable;
#[path = "regression_quoted_printable_soft_line_break.rs"]
pub mod regression_quoted_printable_soft_line_break;
#[path = "regression_quoted_printable_uuid_suffix_suppression.rs"]
pub mod regression_quoted_printable_uuid_suffix_suppression;
#[path = "regression_r2b_detector_fixtures.rs"]
pub mod regression_r2b_detector_fixtures;
#[path = "regression_recall_cloud_providers.rs"]
pub mod regression_recall_cloud_providers;
#[path = "regression_recall_new_prefixes.rs"]
pub mod regression_recall_new_prefixes;
#[path = "regression_recall_vcs_saas.rs"]
pub mod regression_recall_vcs_saas;
#[path = "regression_resolution_algorithmic_dos.rs"]
pub mod regression_resolution_algorithmic_dos;
#[path = "regression_reverse_decode_depth.rs"]
pub mod regression_reverse_decode_depth;
#[path = "regression_reverse_decoy_suppress.rs"]
pub mod regression_reverse_decoy_suppress;
#[path = "regression_reverse_integrity_decoy_suppression.rs"]
pub mod regression_reverse_integrity_decoy_suppression;
#[path = "regression_saas_platform_token_recall.rs"]
pub mod regression_saas_platform_token_recall;
#[path = "regression_scan_telemetry_rayon_scope.rs"]
pub mod regression_scan_telemetry_rayon_scope;
#[path = "regression_shannon_entropy.rs"]
pub mod regression_shannon_entropy;
#[path = "regression_shape_collision_recall_carveout.rs"]
pub mod regression_shape_collision_recall_carveout;
#[path = "regression_simd_label_owner.rs"]
pub mod regression_simd_label_owner;
#[path = "regression_simd_scalar_parity_chunk.rs"]
pub mod regression_simd_scalar_parity_chunk;
#[path = "regression_simdsieve_trigger.rs"]
pub mod regression_simdsieve_trigger;
#[path = "regression_slack_token_family_recall.rs"]
pub mod regression_slack_token_family_recall;
#[path = "regression_ssh2_private_key.rs"]
pub mod regression_ssh2_private_key;
#[path = "regression_stackblitz_backend_parity.rs"]
pub mod regression_stackblitz_backend_parity;
#[path = "regression_strong_anchor_hex_keyword_families.rs"]
pub mod regression_strong_anchor_hex_keyword_families;
#[path = "regression_structured_depth_dos.rs"]
pub mod regression_structured_depth_dos;
#[path = "regression_structured_hcl_generic_recall.rs"]
pub mod regression_structured_hcl_generic_recall;
#[path = "regression_structured_nested_key_recall.rs"]
pub mod regression_structured_nested_key_recall;
#[path = "regression_structured_oversize_partition.rs"]
pub mod regression_structured_oversize_partition;
#[path = "regression_structured_parse_failure_counted.rs"]
pub mod regression_structured_parse_failure_counted;
#[path = "regression_structured_traversal_depth.rs"]
pub mod regression_structured_traversal_depth;
#[path = "regression_suppression_allowlist.rs"]
pub mod regression_suppression_allowlist;
#[path = "regression_suppression_decisions.rs"]
pub mod regression_suppression_decisions;
#[path = "regression_suppression_doc_markers.rs"]
pub mod regression_suppression_doc_markers;
#[path = "regression_suppression_shape_canonical.rs"]
pub mod regression_suppression_shape_canonical;
#[path = "regression_swetrix_capture_group.rs"]
pub mod regression_swetrix_capture_group;
#[path = "regression_symbolic_password_weak_wrappers.rs"]
pub mod regression_symbolic_password_weak_wrappers;
#[path = "regression_telegram_bot_token_recall.rs"]
pub mod regression_telegram_bot_token_recall;
#[path = "regression_trigger_bitmap_proptest.rs"]
pub mod regression_trigger_bitmap_proptest;
#[path = "regression_tuning_bool_override_resolve.rs"]
pub mod regression_tuning_bool_override_resolve;
#[path = "regression_unicode_evasion_norm.rs"]
pub mod regression_unicode_evasion_norm;
#[path = "regression_unicode_hardening_strip.rs"]
pub mod regression_unicode_hardening_strip;
#[path = "regression_url_qp_html_decoders.rs"]
pub mod regression_url_qp_html_decoders;
#[path = "regression_vendor_precision_negative_twin.rs"]
pub mod regression_vendor_precision_negative_twin;
#[path = "regression_vendor_token_right_boundary.rs"]
pub mod regression_vendor_token_right_boundary;
#[path = "regression_webhook_secret_recall.rs"]
pub mod regression_webhook_secret_recall;
#[path = "regression_z85_decode_all.rs"]
pub mod regression_z85_decode_all;
#[path = "regression_z85_reverse_decoders.rs"]
pub mod regression_z85_reverse_decoders;
#[path = "regression_zero_pattern_recompile.rs"]
pub mod regression_zero_pattern_recompile;

// ── Non-`regression_*` standalone tests aggregated to close the scanner
// CI-orphan gap surfaced by the tests_wired.py runs_all_targets fix (DR-341).
// PURE ci-lean-compatible contract/recall/confidence/detector/phase2 tests that
// pass standalone; aggregating them here makes the single `--test all_tests` CI
// step actually run them. Backend-parity/GPU/perf/worklist/env-harness orphans are
// deliberately NOT here (GPU hosts / release timing / corpus env. BACKLOG DR-334).
// Keep sorted.
#[path = "adversarial_a3_decode.rs"]
pub mod adversarial_a3_decode;
#[path = "adversarial_round1_auth_json.rs"]
pub mod adversarial_round1_auth_json;
#[path = "compiled_scanner_detector_digest_stable.rs"]
pub mod compiled_scanner_detector_digest_stable;
#[path = "confidence_floor_edge_cases.rs"]
pub mod confidence_floor_edge_cases;
#[path = "confidence_floor_monotonic.rs"]
pub mod confidence_floor_monotonic;
#[path = "confidence_known_prefix_contract.rs"]
pub mod confidence_known_prefix_contract;
#[path = "cve_corpus_runner.rs"]
pub mod cve_corpus_runner;
#[path = "detector_capture_group_integrity.rs"]
pub mod detector_capture_group_integrity;
#[path = "detector_capture_group_validation.rs"]
pub mod detector_capture_group_validation;
#[path = "detector_inline_test_truth.rs"]
pub mod detector_inline_test_truth;
#[path = "detector_spec_min_confidence_loaded.rs"]
pub mod detector_spec_min_confidence_loaded;
#[path = "gap_floor.rs"]
pub mod gap_floor;
#[path = "high_precision_entropy_disabled.rs"]
pub mod high_precision_entropy_disabled;
#[path = "homoglyph_normalize_consistency.rs"]
pub mod homoglyph_normalize_consistency;
#[path = "pathless_chunk_cpu_recall_parity.rs"]
pub mod pathless_chunk_cpu_recall_parity;
#[path = "pem_private_key_recall_64.rs"]
pub mod pem_private_key_recall_64;
#[path = "per_detector_hostile_near_miss_runner.rs"]
pub mod per_detector_hostile_near_miss_runner;
#[path = "phase2_breakdown.rs"]
pub mod phase2_breakdown;
#[path = "phase2_prefilter_cost_target_spec.rs"]
pub mod phase2_prefilter_cost_target_spec;
#[path = "phase2_prefilter_hs_vs_regexset.rs"]
pub mod phase2_prefilter_hs_vs_regexset;
#[path = "phase2_shard_size.rs"]
pub mod phase2_shard_size;
#[path = "phase2_wire_regression_69.rs"]
pub mod phase2_wire_regression_69;
#[path = "postprocess_confidence_floor.rs"]
pub mod postprocess_confidence_floor;
#[path = "preprocessor_no_phantom_append.rs"]
pub mod preprocessor_no_phantom_append;
#[path = "property_segment_attribution.rs"]
pub mod property_segment_attribution;
#[path = "readme_claims.rs"]
pub mod readme_claims;
#[path = "scan_coalesced_reference_determinism.rs"]
pub mod scan_coalesced_reference_determinism;
#[path = "scan_probe.rs"]
pub mod scan_probe;
#[path = "adversarial/segment_attribution_adversarial.rs"]
pub mod segment_attribution_adversarial;
#[path = "simd_cross_os_no_ungated_ffi.rs"]
pub mod simd_cross_os_no_ungated_ffi;
#[path = "simd_scratch_oversubscription.rs"]
pub mod simd_scratch_oversubscription;
#[path = "som_window_localization_ceiling.rs"]
pub mod som_window_localization_ceiling;
#[path = "stripe_direct_prefix_dedup.rs"]
pub mod stripe_direct_prefix_dedup;
#[path = "structured_hcl_parser_contract.rs"]
pub mod structured_hcl_parser_contract;
#[path = "structured_yaml_alias_contract.rs"]
pub mod structured_yaml_alias_contract;
#[path = "telemetry_dogfood_silent_path_contract.rs"]
pub mod telemetry_dogfood_silent_path_contract;
#[path = "testing_facade_compile_contract.rs"]
pub mod testing_facade_compile_contract;
#[path = "unit_a3_decode.rs"]
pub mod unit_a3_decode;
#[path = "unit_a3_multiline.rs"]
pub mod unit_a3_multiline;
#[path = "unit_a3_pipeline.rs"]
pub mod unit_a3_pipeline;
#[path = "unit_checksum_live.rs"]
pub mod unit_checksum_live;
#[path = "unit_compiler_prefix_live.rs"]
pub mod unit_compiler_prefix_live;
#[path = "unit_engine_cases_live.rs"]
pub mod unit_engine_cases_live;
#[path = "vendorgen_harness_contract.rs"]
pub mod vendorgen_harness_contract;
#[path = "window_boundary.rs"]
pub mod window_boundary;
