#![allow(clippy::needless_borrow, clippy::needless_update, clippy::useless_vec)]

pub mod concurrent;
pub mod contract;
pub mod integration;
pub mod regression;
// Standalone `regression_*.rs` files are aggregated here so the single CI step
// `cargo test -p keyhog-scanner --test all_tests` actually runs them. A test file
// that lives in `tests/` but is NOT `#[path]`-included here (and not explicitly
// `--test`-listed in a workflow) is a CI-orphan: it never runs, its assertions
// are dead weight, and the regression it guards can ship silently. The
// `scripts/gates/recall_locks_wired.py` gate fails the build if any top-level
// `regression_*.rs` is orphaned, so this list stays exhaustive. Keep sorted.
#[path = "regression_ai_provider_key_recall.rs"]
pub mod regression_ai_provider_key_recall;
#[path = "regression_ai_vendor_prefix_token_recall.rs"]
pub mod regression_ai_vendor_prefix_token_recall;
#[path = "regression_bare_authorization_no_fp.rs"]
pub mod regression_bare_authorization_no_fp;
#[path = "regression_bare_service_url_recall.rs"]
pub mod regression_bare_service_url_recall;
#[path = "regression_billing_vendor_token_recall.rs"]
pub mod regression_billing_vendor_token_recall;
#[path = "regression_cloud_credential_recall.rs"]
pub mod regression_cloud_credential_recall;
#[path = "regression_cloud_infra_db_token_recall.rs"]
pub mod regression_cloud_infra_db_token_recall;
#[path = "regression_coalesced_reassembly_parity.rs"]
pub mod regression_coalesced_reassembly_parity;
#[path = "regression_context_syntax_recall.rs"]
pub mod regression_context_syntax_recall;
#[path = "regression_creddata_hex_key_recall.rs"]
pub mod regression_creddata_hex_key_recall;
#[path = "regression_creddata_key_anchor_precision_contract.rs"]
pub mod regression_creddata_key_anchor_precision_contract;
#[path = "regression_creddata_keyword_suffix_recall.rs"]
pub mod regression_creddata_keyword_suffix_recall;
#[path = "regression_creddata_random_password_recall.rs"]
pub mod regression_creddata_random_password_recall;
#[path = "regression_creddata_sql_cli_password_recall.rs"]
pub mod regression_creddata_sql_cli_password_recall;
#[path = "regression_creddata_url_credentials_recall.rs"]
pub mod regression_creddata_url_credentials_recall;
#[path = "regression_creddata_vendor_prefixed_key_recall.rs"]
pub mod regression_creddata_vendor_prefixed_key_recall;
#[path = "regression_credential_uri_scheme_coverage.rs"]
pub mod regression_credential_uri_scheme_coverage;
#[path = "regression_crlf_entropy_line_offsets.rs"]
pub mod regression_crlf_entropy_line_offsets;
#[path = "regression_db_connection_string_recall.rs"]
pub mod regression_db_connection_string_recall;
#[path = "regression_decode_through_strict.rs"]
pub mod regression_decode_through_strict;
#[path = "regression_deepl_bare_key_recall.rs"]
pub mod regression_deepl_bare_key_recall;
#[path = "regression_devplatform_monitoring_token_recall.rs"]
pub mod regression_devplatform_monitoring_token_recall;
#[path = "regression_devtool_vendor_token_recall.rs"]
pub mod regression_devtool_vendor_token_recall;
#[path = "regression_dogfood_policy_prose_precision.rs"]
pub mod regression_dogfood_policy_prose_precision;
#[path = "regression_dot_concatenation.rs"]
pub mod regression_dot_concatenation;
#[path = "regression_dotfile_credentials.rs"]
pub mod regression_dotfile_credentials;
#[path = "regression_dotted_authentication_key_recall.rs"]
pub mod regression_dotted_authentication_key_recall;
#[path = "regression_edge_platform_token_recall.rs"]
pub mod regression_edge_platform_token_recall;
#[path = "regression_email_vendor_token_recall.rs"]
pub mod regression_email_vendor_token_recall;
#[path = "regression_encoded_benign_text_suppression.rs"]
pub mod regression_encoded_benign_text_suppression;
#[path = "regression_entropy_base64_protobuf_decoys.rs"]
pub mod regression_entropy_base64_protobuf_decoys;
#[path = "regression_generic_bridge_padded_log_field.rs"]
pub mod regression_generic_bridge_padded_log_field;
#[path = "regression_github_app_pem_boundary.rs"]
pub mod regression_github_app_pem_boundary;
#[path = "regression_github_pat_boundary.rs"]
pub mod regression_github_pat_boundary;
#[path = "regression_gitlab_token_completeness_recall.rs"]
pub mod regression_gitlab_token_completeness_recall;
#[path = "regression_hexbody_vendor_prefix_floor.rs"]
pub mod regression_hexbody_vendor_prefix_floor;
#[path = "regression_hot_path_fp_context_parity.rs"]
pub mod regression_hot_path_fp_context_parity;
#[path = "regression_hot_pattern_process_parity.rs"]
pub mod regression_hot_pattern_process_parity;
#[path = "regression_hot_token_right_boundary.rs"]
pub mod regression_hot_token_right_boundary;
#[path = "regression_iac_secret_recall.rs"]
pub mod regression_iac_secret_recall;
#[path = "regression_infra_vendor_token_recall.rs"]
pub mod regression_infra_vendor_token_recall;
#[path = "regression_into_matches_dedup_order_invariant.rs"]
pub mod regression_into_matches_dedup_order_invariant;
#[path = "regression_jwt_header_field_order_recall.rs"]
pub mod regression_jwt_header_field_order_recall;
#[path = "regression_jwt_signing_secret_recall.rs"]
pub mod regression_jwt_signing_secret_recall;
#[path = "regression_keyword_predicate_union.rs"]
pub mod regression_keyword_predicate_union;
#[path = "regression_kubeconfig_k8s_recall.rs"]
pub mod regression_kubeconfig_k8s_recall;
#[path = "regression_messaging_vendor_token_recall.rs"]
pub mod regression_messaging_vendor_token_recall;
#[path = "regression_observability_ci_token_recall.rs"]
pub mod regression_observability_ci_token_recall;
#[path = "regression_observability_token_recall.rs"]
pub mod regression_observability_token_recall;
#[path = "regression_overbroad_detectors_precision.rs"]
pub mod regression_overbroad_detectors_precision;
#[path = "regression_package_registry_token_recall.rs"]
pub mod regression_package_registry_token_recall;
#[path = "regression_password_slot_mask_suppression.rs"]
pub mod regression_password_slot_mask_suppression;
#[path = "regression_payment_vendor_token_recall.rs"]
pub mod regression_payment_vendor_token_recall;
#[path = "regression_private_key_block_resolution.rs"]
pub mod regression_private_key_block_resolution;
#[path = "regression_private_key_caesar_decode_suppression.rs"]
pub mod regression_private_key_caesar_decode_suppression;
#[path = "regression_private_key_decode_child_resolution.rs"]
pub mod regression_private_key_decode_child_resolution;
#[path = "regression_private_key_variant_matrix.rs"]
pub mod regression_private_key_variant_matrix;
#[path = "regression_putty_private_key.rs"]
pub mod regression_putty_private_key;
#[path = "regression_quoted_printable_uuid_suffix_suppression.rs"]
pub mod regression_quoted_printable_uuid_suffix_suppression;
#[path = "regression_recall_new_prefixes.rs"]
pub mod regression_recall_new_prefixes;
#[path = "regression_resolution_algorithmic_dos.rs"]
pub mod regression_resolution_algorithmic_dos;
#[path = "regression_reverse_integrity_decoy_suppression.rs"]
pub mod regression_reverse_integrity_decoy_suppression;
#[path = "regression_saas_platform_token_recall.rs"]
pub mod regression_saas_platform_token_recall;
#[path = "regression_shape_collision_recall_carveout.rs"]
pub mod regression_shape_collision_recall_carveout;
#[path = "regression_slack_token_family_recall.rs"]
pub mod regression_slack_token_family_recall;
#[path = "regression_ssh2_private_key.rs"]
pub mod regression_ssh2_private_key;
#[path = "regression_strong_anchor_hex_keyword_families.rs"]
pub mod regression_strong_anchor_hex_keyword_families;
#[path = "regression_structured_hcl_generic_recall.rs"]
pub mod regression_structured_hcl_generic_recall;
#[path = "regression_structured_nested_key_recall.rs"]
pub mod regression_structured_nested_key_recall;
#[path = "regression_structured_oversize_partition.rs"]
pub mod regression_structured_oversize_partition;
#[path = "regression_structured_parse_failure_counted.rs"]
pub mod regression_structured_parse_failure_counted;
#[path = "regression_symbolic_password_weak_wrappers.rs"]
pub mod regression_symbolic_password_weak_wrappers;
#[path = "regression_telegram_bot_token_recall.rs"]
pub mod regression_telegram_bot_token_recall;
#[path = "regression_vendor_precision_negative_twin.rs"]
pub mod regression_vendor_precision_negative_twin;
#[path = "regression_vendor_token_right_boundary.rs"]
pub mod regression_vendor_token_right_boundary;
#[path = "regression_webhook_secret_recall.rs"]
pub mod regression_webhook_secret_recall;
#[path = "regression_zero_pattern_recompile.rs"]
pub mod regression_zero_pattern_recompile;
