//! Regression and property coverage for the selective literal-anchor prefilter.

use keyhog_scanner::testing::BigramBloom;
use keyhog_scanner::BigramPrefilterState;
use proptest::prelude::*;

fn bloom(literals: &[&str]) -> BigramBloom {
    BigramBloom::from_literal_prefixes(
        &literals
            .iter()
            .map(|literal| (*literal).to_owned())
            .collect::<Vec<_>>(),
    )
}

#[test]
fn complete_literal_admits_and_unrelated_text_rejects() {
    let filter = bloom(&["ghp_"]);
    assert!(filter.maybe_overlaps(b"token=ghp_0123456789"));
    assert!(!filter.maybe_overlaps(b"completely unrelated source text"));
}

#[test]
fn every_literal_alternative_remains_reachable() {
    let filter = bloom(&["ALPHA_service_key", "OMEGA_access_token", "://"]);
    for literal in ["ALPHA_service_key", "OMEGA_access_token", "://"] {
        assert!(
            filter.maybe_overlaps(format!("prefix {literal} suffix").as_bytes()),
            "mandatory alternative {literal:?} was rejected"
        );
    }
    assert!(!filter.maybe_overlaps(b"zzzzzzzzzzzzzzzzzzzzzzzzzz"));
}

#[test]
fn selected_anchor_is_ascii_case_insensitive() {
    let filter = bloom(&["AbCd_"]);
    for candidate in ["AbCd_", "abcd_", "ABCD_", "aBcD_"] {
        assert!(filter.maybe_overlaps(candidate.as_bytes()));
    }
    assert!(!filter.maybe_overlaps(b"abce_"));
}

#[test]
fn one_to_four_byte_anchor_widths_are_sound() {
    for literal in ["x", "xy", "xyz", "xyzw", "xyzwa"] {
        let filter = bloom(&[literal]);
        assert!(filter.maybe_overlaps(literal.as_bytes()));
        assert!(filter.maybe_overlaps(format!("before{literal}after").as_bytes()));
    }
}

#[test]
fn chunks_shorter_than_the_selected_anchor_fail_open() {
    let filter = bloom(&["ghp_"]);
    for chunk in [&b""[..], &b"g"[..], &b"gh"[..], &b"ghp"[..]] {
        assert!(filter.maybe_overlaps(chunk));
    }
}

#[test]
fn utf8_literal_is_byte_exact_and_sound() {
    let filter = bloom(&["🔑"]);
    assert!(filter.maybe_overlaps("prefix🔑suffix".as_bytes()));
    assert!(!filter.maybe_overlaps("🔒".as_bytes()));
}

#[test]
fn empty_or_unanchorable_corpus_is_invalid_and_fails_open() {
    for literals in [&[][..], &[""][..], &["SAFE_ANCHOR", ""][..]] {
        let filter = bloom(literals);
        assert_eq!(filter.status().state, BigramPrefilterState::Invalid);
        assert!(filter.maybe_overlaps(b"unrelated bytes must be admitted"));
    }
}

#[test]
fn overlap_is_found_at_front_middle_and_tail() {
    let filter = bloom(&["ghp_"]);
    for chunk in [
        b"ghp_zzzzzz".as_slice(),
        b"zzzzghp_zz".as_slice(),
        b"zzzzzzghp_".as_slice(),
    ] {
        assert!(filter.maybe_overlaps(chunk));
    }
}

#[test]
fn clone_preserves_queries_and_status() {
    let original = bloom(&["ghp_", "AKIA"]);
    let cloned = original.clone();
    for probe in [
        b"ghp_candidate".as_slice(),
        b"akia_candidate".as_slice(),
        b"unrelated source".as_slice(),
    ] {
        assert_eq!(original.maybe_overlaps(probe), cloned.maybe_overlaps(probe));
    }
    assert_eq!(original.status(), cloned.status());
}

#[test]
fn saturation_and_invalid_states_fail_open() {
    let saturated = BigramBloom::with_population_for_test(39_322);
    assert_eq!(saturated.status().state, BigramPrefilterState::Saturated);
    assert!(saturated.maybe_overlaps(b"definitely absent"));

    let invalid = BigramBloom::invalid_for_test();
    assert_eq!(invalid.status().state, BigramPrefilterState::Invalid);
    assert!(invalid.maybe_overlaps(b"definitely absent"));
}

fn ascii_string(bytes: &[u8]) -> String {
    String::from_utf8(bytes.to_vec()).expect("generated bytes are printable ASCII")
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(4_000))]

    #[test]
    fn embedded_literal_is_never_a_false_negative(
        literal in prop::collection::vec(0x21u8..=0x7e, 1..24),
        pre in prop::collection::vec(any::<u8>(), 0..80),
        post in prop::collection::vec(any::<u8>(), 0..80),
    ) {
        let literal = ascii_string(&literal);
        let filter = BigramBloom::from_literal_prefixes(std::slice::from_ref(&literal));
        let mut chunk = pre;
        chunk.extend_from_slice(literal.as_bytes());
        chunk.extend_from_slice(&post);
        prop_assert!(filter.maybe_overlaps(&chunk));
    }

    #[test]
    fn every_member_of_an_alternative_set_is_never_a_false_negative(
        literals in prop::collection::vec(
            prop::collection::vec(0x21u8..=0x7e, 1..16),
            1..12,
        ),
        selected in any::<usize>(),
    ) {
        let literals: Vec<String> = literals.iter().map(|bytes| ascii_string(bytes)).collect();
        let filter = BigramBloom::from_literal_prefixes(&literals);
        let literal = &literals[selected % literals.len()];
        let chunk = format!("before{literal}after");
        prop_assert!(filter.maybe_overlaps(chunk.as_bytes()));
    }
}
