//! Migrated from `src/auto_fix.rs` inline tests.
#[test]
fn curated_services_map_correctly() {
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "aws"
        ),
        "AWS_ACCESS_KEY_ID"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "aws-iam"
        ),
        "AWS_ACCESS_KEY_ID"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "github"
        ),
        "GITHUB_TOKEN"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "GitHub"
        ),
        "GITHUB_TOKEN"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "openai"
        ),
        "OPENAI_API_KEY"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "anthropic"
        ),
        "ANTHROPIC_API_KEY"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "stripe"
        ),
        "STRIPE_SECRET_KEY"
    );
    assert_eq!(
        keyhog_core::testing::CoreTestApi::auto_fix_env_var_name_for_service(
            &keyhog_core::testing::TestApi,
            "snowflake"
        ),
        "SNOWFLAKE_PASSWORD"
    );
}
