//! Random-token vs dictionary-identifier discriminator (KH-L-0413).
//!
//! The generic keyword bridge suppresses any value the identifier/type-name
//! shape gates flag (`pure_identifier_no_digit`, `pure_identifier`,
//! `type_name_shape`, `word_separated_identifier`). Those gates exist to drop
//! code references — `password = getUserName`, `secret = configValue` — but they
//! ALSO drop a large pool of REAL random passwords that happen to be all-letters
//! with no digit (`GRAPHITE_PASS=gjbubxsu`, `password="ufnlbbavawsdeecn"`,
//! `ftp://user:pxidztpv`): on CredData ~1114 keyword-anchored positives, measured
//! via the KH-L-0412 `--dogfood` trace.
//!
//! The two classes are SHAPE-identical (lowercase, no digit), so the only sound
//! discriminator is LANGUAGE STRUCTURE: a real random password has improbable
//! letter adjacencies (`gjb`, `xs`, `dz`), a dictionary identifier is built from
//! pronounceable English fragments (`get`, `user`, `config`). We score the mean
//! adjacent-bigram log-probability of the value's alphabetic runs against an
//! English bigram model (`data/english_bigram_logprob.bin`, generated by
//! `ml/gen_bigram_model.py` from a standard wordlist). A value whose letters are
//! collectively IMPROBABLE under English (mean log-prob below a threshold) is a
//! random token; a pronounceable one is a dictionary identifier.
//!
//! This is the SOUND half of the lever: lifting the identifier gates
//! unconditionally recovered +1023 CredData TP but added +3554 FP (precision
//! 0.60→0.40) by surfacing every `password = someVariable`; gating the lift on
//! `is_random_token` keeps the random passwords while leaving the identifier
//! references suppressed. Verified on BOTH bench corpora before landing.

use std::sync::LazyLock;

/// English bigram log-probabilities, row-major `[a][b]` over `'a'..='z'`,
/// little-endian f32. Generated + committed by `ml/gen_bigram_model.py`; the
/// `.bin` is the reproducible source of truth (host-independent).
const BIGRAM_LOGPROB_BYTES: &[u8] = include_bytes!("../../data/english_bigram_logprob.bin");

/// Parsed 26×26 model. Built once; the hot path indexes `[a*26 + b]`.
static BIGRAM_LOGPROB: LazyLock<[f32; 676]> = LazyLock::new(|| {
    assert_eq!(
        BIGRAM_LOGPROB_BYTES.len(),
        676 * 4,
        "english_bigram_logprob.bin must hold exactly 26*26 little-endian f32 \
         (regenerate with ml/gen_bigram_model.py)"
    );
    let mut t = [0.0f32; 676];
    for (i, slot) in t.iter_mut().enumerate() {
        let b = &BIGRAM_LOGPROB_BYTES[i * 4..i * 4 + 4];
        *slot = f32::from_le_bytes([b[0], b[1], b[2], b[3]]);
    }
    t
});

/// Minimum alphabetic characters before a randomness verdict is meaningful.
/// Below this, English bigram statistics are too sparse to separate a short
/// random password from a short identifier, so we return `false` (NOT random ⇒
/// the identifier gate keeps suppressing — fail safe toward precision).
const MIN_ALPHA: usize = 6;

/// Mean adjacent-bigram log-probability at or below which a token's letters are
/// collectively too improbable for English ⇒ a random token, not a dictionary
/// identifier. Calibrated on the CredData real-password vs identifier pools so
/// random passwords (≤ ~−7) pass while dictionary identifiers (≥ ~−6.4) do not;
/// the model's clean separation gap sits around −6.7.
const RANDOM_LOGPROB_THRESHOLD: f32 = -6.85;

/// Mean adjacent-bigram log-probability over the value's alphabetic runs, or
/// `None` when there are too few alphabetic bigrams to judge. Bigrams are only
/// counted between two ADJACENT ASCII letters (a digit/symbol breaks the run),
/// so an embedded digit never bridges an improbable cross-segment pair.
pub(crate) fn mean_bigram_logprob(value: &str) -> Option<f32> {
    let table = &*BIGRAM_LOGPROB;
    let bytes = value.as_bytes();
    let mut sum = 0.0f32;
    let mut pairs = 0u32;
    let mut alpha = 0usize;
    let mut prev: Option<usize> = None;
    for &byte in bytes {
        if byte.is_ascii_alphabetic() {
            alpha += 1;
            let idx = (byte.to_ascii_lowercase() - b'a') as usize;
            if let Some(p) = prev {
                sum += table[p * 26 + idx];
                pairs += 1;
            }
            prev = Some(idx);
        } else {
            // digit / symbol ends the current alphabetic run
            prev = None;
        }
    }
    if alpha < MIN_ALPHA || pairs == 0 {
        return None;
    }
    Some(sum / pairs as f32)
}

/// `true` iff `value` reads as a RANDOM token (real credential) rather than a
/// pronounceable dictionary identifier (code reference). Fails safe to `false`
/// (treat as identifier ⇒ keep suppressing) when the value is too short/sparse
/// to judge — soundness over reach.
pub(crate) fn is_random_token(value: &str) -> bool {
    match mean_bigram_logprob(value) {
        Some(score) => score <= RANDOM_LOGPROB_THRESHOLD,
        None => false,
    }
}
