prefixes = [
    "sk-proj-",
    "sk-svcacct-",
    "sk-admin-",
    "sk_live_",
    "sk_test_",
    "rk_live_",
    "pk_live_",
    "ghp_",
    "ghs_",
    "gho_",
    "ghu_",
    "ghr_",
    "github_pat_",
    "xoxb-",
    "xoxp-",
    "xoxa-",
    "xoxr-",
    "xoxs-",
    "xapp-",
    "sk-ant-",
    "hf_",
    ".iam.gserviceaccount.com",
    "glpat-",
    "npm_",
    "HRKU-",
]
