needles = [
  "secretscanner",
  "secret-scanner",
  "secret_scanner",
  "credentialscanner",
  "credential-scanner",
  "credential_scanner",
  "trufflehog",
  "gitleaks",
  "detect-secrets",
  "detect_secrets",
]

vendored_js_prefixes = [
  "bootstrap",
  "jquery",
  "react.",
  "react-",
  "vue.",
  "vue-",
  "angular",
  "ember",
  "backbone",
  "lodash",
  "underscore",
  "moment",
  "alertify",
  "fullcalendar",
  "datatables",
  "highcharts",
  "chart.",
  "chart-",
  "select2",
  "tinymce",
  "ckeditor",
  "codemirror",
  "html5",
  "modernizr",
  "respond",
]
