suffixes = [
  ")/g",
  ")/g,",
  ")/gi",
  ")/gi,",
  ")/i",
  ")/i,",
  ")/m",
  ")/m,",
  ")\\b",
  "})\\b",
  "})\\\\b",
  "]+",
  "]*",
  "]?",
  "]+/",
  "]+\\b",
  "*/g",
  "+/g",
  "+/i",
  ")*",
  ")+",
  ")?",
  ")?$",
  ")$",
]
