source_types = [
  "filesystem",
  "git",
  "git/head",
  "git/history",
  "git/tag",
  "git/unreachable",
  "git/diff",
  "git/staged",
  "git-diff",
  "git-history",
  "stdin",
  "s3",
  "docker",
  "web",
  "github",
  "slack",
  "binary",
]
