suffixes = [
  "atlassian.net",
  "auth0.com",
  "azure-api.net",
  "azurewebsites.net",
  "firebaseapp.com",
  "firebaseio.com",
  "herokuapp.com",
  "jfrog.io",
  "mongodb.net",
  "myshopify.com",
  "netlify.app",
  "on.aws",
  "openai.azure.com",
  "supabase.co",
  "upstash.io",
  "vercel.app",
  "windows.net",
]
